// Profiles of all 66 books. Dates are traditional / approximate; where
// authorship is debated the entry says "traditionally" or names the view.
// outline: [fromChapter, toChapter, title]
export const BOOK_INFO = {
  gen: { genre: 'Law (Torah)', author: 'Moses (traditional)', date: 'c. 1440–1400 BC', audience: 'Israel in the wilderness',
    theme: 'Beginnings — creation, fall, and God’s covenant promise through Abraham’s family.',
    summary: 'Genesis tells how God created a good world, how humanity fell into sin, and how God began His rescue plan by calling Abraham and promising that through his offspring all nations would be blessed. The book follows the patriarchs Abraham, Isaac, Jacob and Joseph, ending with Israel’s family in Egypt.',
    keyVerses: ['Genesis 1:1', 'Genesis 3:15', 'Genesis 12:2-3', 'Genesis 50:20'],
    outline: [[1, 2, 'Creation'], [3, 11, 'The fall, the flood and Babel'], [12, 25, 'Abraham'], [25, 36, 'Isaac and Jacob'], [37, 50, 'Joseph']],
    christ: 'The promised “seed of the woman” (3:15) who will crush the serpent, and the offspring of Abraham who blesses all nations (Galatians 3:16).' },
  exo: { genre: 'Law (Torah)', author: 'Moses (traditional)', date: 'c. 1440–1400 BC', audience: 'Israel',
    theme: 'Redemption — God rescues His people from slavery and comes to dwell among them.',
    summary: 'Exodus records Israel’s slavery in Egypt, God’s call of Moses at the burning bush, the ten plagues, the Passover and the crossing of the Red Sea. At Mount Sinai God gives the Ten Commandments and instructions for the tabernacle, where His glory comes to dwell with His people.',
    keyVerses: ['Exodus 3:14', 'Exodus 12:13', 'Exodus 14:14', 'Exodus 20:2-3'],
    outline: [[1, 12, 'Slavery and the plagues'], [13, 18, 'Exodus and the journey to Sinai'], [19, 24, 'The covenant and the Law'], [25, 40, 'The tabernacle']],
    christ: 'Jesus is the Passover Lamb (1 Corinthians 5:7) and the true dwelling of God with us (John 1:14).' },
  lev: { genre: 'Law (Torah)', author: 'Moses (traditional)', date: 'c. 1440–1400 BC', audience: 'Israel’s priests and people',
    theme: 'Holiness — how a sinful people can live in the presence of a holy God.',
    summary: 'Leviticus explains the sacrifices, the priesthood, the laws of clean and unclean, and the annual feasts, including the Day of Atonement. Its refrain is “be holy, for I am holy.”',
    keyVerses: ['Leviticus 17:11', 'Leviticus 19:2', 'Leviticus 19:18'],
    outline: [[1, 7, 'Offerings'], [8, 10, 'The priesthood'], [11, 16, 'Clean and unclean; Day of Atonement'], [17, 27, 'The holiness code']],
    christ: 'Hebrews shows Jesus as the great High Priest and the once-for-all sacrifice the offerings pointed to (Hebrews 9:11-14).' },
  num: { genre: 'Law (Torah)', author: 'Moses (traditional)', date: 'c. 1440–1400 BC', audience: 'Israel',
    theme: 'God’s faithfulness through forty years of Israel’s unbelief in the wilderness.',
    summary: 'Numbers takes its name from two censuses of Israel. Between them, the people refuse to enter Canaan out of fear and wander for forty years. Even so, God provides manna, water and guidance, and preserves a new generation for the promised land.',
    keyVerses: ['Numbers 6:24-26', 'Numbers 14:18', 'Numbers 23:19'],
    outline: [[1, 10, 'Preparing at Sinai'], [11, 25, 'Rebellion and wandering'], [26, 36, 'A new generation on the plains of Moab']],
    christ: 'The bronze serpent lifted up for healing (21:9) is a picture Jesus applied to His own cross (John 3:14-15).' },
  deu: { genre: 'Law (Torah)', author: 'Moses (traditional)', date: 'c. 1406 BC', audience: 'The new generation about to enter Canaan',
    theme: 'Covenant renewal — love the LORD with all your heart and obey Him.',
    summary: 'Deuteronomy (“second law”) is Moses’ farewell sermons on the plains of Moab. He reviews Israel’s history, restates the Law, and calls the people to love God wholeheartedly and choose life. It ends with Moses’ death.',
    keyVerses: ['Deuteronomy 6:4-5', 'Deuteronomy 8:3', 'Deuteronomy 31:6', 'Deuteronomy 30:19'],
    outline: [[1, 4, 'Looking back'], [5, 26, 'The Law restated'], [27, 30, 'Blessings, curses and choosing life'], [31, 34, 'Moses’ farewell']],
    christ: 'Jesus quoted Deuteronomy to defeat temptation (Matthew 4:4-10) and is the Prophet like Moses (18:15; Acts 3:22).' },
  jos: { genre: 'History', author: 'Joshua with later editing (traditional)', date: 'c. 1400–1370 BC', audience: 'Israel',
    theme: 'God keeps His promises — Israel takes possession of the land.',
    summary: 'Joshua leads Israel across the Jordan, through the fall of Jericho and the conquest of Canaan, and divides the land among the tribes. He ends by challenging the nation: “choose you this day whom ye will serve.”',
    keyVerses: ['Joshua 1:9', 'Joshua 21:45', 'Joshua 24:15'],
    outline: [[1, 5, 'Entering the land'], [6, 12, 'Conquering the land'], [13, 21, 'Dividing the land'], [22, 24, 'Joshua’s farewell']],
    christ: 'Joshua (Hebrew Yeshua, “the LORD saves”) shares Jesus’ name and leads God’s people into rest (Hebrews 4:8-9).' },
  jdg: { genre: 'History', author: 'Unknown (traditionally Samuel)', date: 'c. 1050–1000 BC', audience: 'Israel',
    theme: 'A cycle of sin, oppression, crying out and deliverance — “every man did that which was right in his own eyes.”',
    summary: 'Judges covers the turbulent period between Joshua and the kings. Israel repeatedly turns to idols, falls under enemies, cries to God, and is rescued by judges such as Deborah, Gideon and Samson. The book shows the need for a faithful king.',
    keyVerses: ['Judges 2:16', 'Judges 6:12', 'Judges 21:25'],
    outline: [[1, 2, 'Incomplete conquest'], [3, 16, 'The judges'], [17, 21, 'Moral collapse']],
    christ: 'Every flawed deliverer points to the perfect Deliverer and King Israel needed.' },
  rut: { genre: 'History', author: 'Unknown', date: 'Events in the time of the judges; written during the monarchy', audience: 'Israel',
    theme: 'Loyal love and redemption — God’s providence in ordinary lives.',
    summary: 'Ruth, a Moabite widow, refuses to leave her mother-in-law Naomi: “whither thou goest, I will go.” In Bethlehem, Boaz acts as kinsman-redeemer and marries her. Their son Obed becomes the grandfather of King David.',
    keyVerses: ['Ruth 1:16', 'Ruth 2:12', 'Ruth 4:14'],
    outline: [[1, 1, 'Loss and loyalty'], [2, 2, 'Gleaning in Boaz’s field'], [3, 3, 'At the threshing floor'], [4, 4, 'Redemption and a son']],
    christ: 'Boaz the kinsman-redeemer pictures Christ, who redeems us at His own cost; Ruth is in Jesus’ genealogy (Matthew 1:5).' },
  '1sa': { genre: 'History', author: 'Unknown (includes records of Samuel, Nathan and Gad)', date: 'c. 930 BC or later', audience: 'Israel',
    theme: 'The transition from judges to kings — God looks on the heart.',
    summary: '1 Samuel tells of Hannah’s prayer and Samuel’s birth, Israel’s demand for a king, Saul’s rise and failure, and God’s choice of the shepherd boy David, who defeats Goliath and waits patiently while Saul pursues him.',
    keyVerses: ['1 Samuel 2:2', '1 Samuel 15:22', '1 Samuel 16:7', '1 Samuel 17:47'],
    outline: [[1, 7, 'Samuel'], [8, 15, 'Saul becomes king'], [16, 31, 'David and Saul']],
    christ: 'David, the anointed shepherd-king from Bethlehem, foreshadows Jesus, the Son of David.' },
  '2sa': { genre: 'History', author: 'Unknown', date: 'c. 930 BC or later', audience: 'Israel',
    theme: 'David’s reign — God’s everlasting covenant, and the real cost of sin.',
    summary: '2 Samuel records David becoming king over all Israel, bringing the ark to Jerusalem and receiving God’s promise of an everlasting throne (chapter 7). It honestly records his sin with Bathsheba, his repentance, and the turmoil that follows in his family.',
    keyVerses: ['2 Samuel 7:12-13', '2 Samuel 7:22', '2 Samuel 12:13', '2 Samuel 22:2-3'],
    outline: [[1, 10, 'David’s triumphs'], [11, 12, 'David’s sin'], [13, 24, 'David’s troubles']],
    christ: 'The covenant of 2 Samuel 7 is fulfilled in Jesus, whose kingdom has no end (Luke 1:32-33).' },
  '1ki': { genre: 'History', author: 'Unknown (traditionally Jeremiah)', date: 'c. 560–540 BC', audience: 'Israel in exile',
    theme: 'Faithfulness brings blessing; idolatry divides and destroys the kingdom.',
    summary: '1 Kings begins with Solomon’s wisdom and the building of the temple, then his decline into idolatry. The kingdom splits into Israel (north) and Judah (south). The prophet Elijah confronts King Ahab and the prophets of Baal on Mount Carmel.',
    keyVerses: ['1 Kings 3:9', '1 Kings 8:27', '1 Kings 18:21', '1 Kings 19:12'],
    outline: [[1, 11, 'Solomon'], [12, 16, 'The divided kingdom'], [17, 22, 'Elijah and Ahab']],
    christ: 'Jesus is “greater than Solomon” (Matthew 12:42) and the true temple (John 2:19-21).' },
  '2ki': { genre: 'History', author: 'Unknown (traditionally Jeremiah)', date: 'c. 560–540 BC', audience: 'Israel in exile',
    theme: 'The long road to exile — and God’s patience through His prophets.',
    summary: '2 Kings follows Elisha’s ministry and the kings of Israel and Judah. Israel falls to Assyria in 722 BC; Judah, despite reforms under Hezekiah and Josiah, falls to Babylon in 586 BC and Jerusalem is destroyed.',
    keyVerses: ['2 Kings 6:16', '2 Kings 17:13', '2 Kings 22:2'],
    outline: [[1, 8, 'Elisha'], [9, 17, 'Kings until Israel’s fall'], [18, 25, 'Judah until exile']],
    christ: 'Elisha’s miracles — feeding a crowd, healing a leper, raising a son — anticipate the ministry of Jesus.' },
  '1ch': { genre: 'History', author: 'Ezra (traditional; “the Chronicler”)', date: 'c. 450–400 BC', audience: 'Jews returned from exile',
    theme: 'God’s people, David’s line and true worship — written to encourage the returned exiles.',
    summary: '1 Chronicles retells Israel’s history from Adam to David with long genealogies and a focus on David’s preparations for the temple and the organization of worship.',
    keyVerses: ['1 Chronicles 4:10', '1 Chronicles 16:11', '1 Chronicles 29:11'],
    outline: [[1, 9, 'Genealogies'], [10, 21, 'David’s reign'], [22, 29, 'Preparing for the temple']],
    christ: 'The genealogies preserve the royal line that leads to Jesus the Messiah.' },
  '2ch': { genre: 'History', author: 'Ezra (traditional; “the Chronicler”)', date: 'c. 450–400 BC', audience: 'Jews returned from exile',
    theme: 'Humble repentance brings restoration.',
    summary: '2 Chronicles covers Solomon’s temple and the kings of Judah, highlighting revivals under Asa, Jehoshaphat, Hezekiah and Josiah. It ends with Cyrus’ decree allowing the exiles to return.',
    keyVerses: ['2 Chronicles 7:14', '2 Chronicles 16:9', '2 Chronicles 20:15'],
    outline: [[1, 9, 'Solomon'], [10, 36, 'The kings of Judah']],
    christ: 'The promise of restoration after repentance is ultimately fulfilled through Christ.' },
  ezr: { genre: 'History', author: 'Ezra (traditional)', date: 'c. 440 BC', audience: 'The returned exiles',
    theme: 'Return and rebuilding — restoring the temple and God’s Word to the center.',
    summary: 'Ezra records the first return under Zerubbabel and the rebuilding of the temple, then Ezra’s own return to teach the Law and call the people to repentance.',
    keyVerses: ['Ezra 7:10', 'Ezra 8:22'],
    outline: [[1, 6, 'Rebuilding the temple'], [7, 10, 'Ezra’s reforms']],
    christ: 'God faithfully preserves His people and His promises leading to the Messiah.' },
  neh: { genre: 'History', author: 'Nehemiah (memoir)', date: 'c. 430 BC', audience: 'The returned exiles',
    theme: 'Prayerful leadership — rebuilding Jerusalem’s walls in 52 days despite opposition.',
    summary: 'Nehemiah, cupbearer to the Persian king, prays and then leads the rebuilding of Jerusalem’s walls. He faces mockery, threats and internal injustice, and with Ezra leads a revival around the reading of the Law.',
    keyVerses: ['Nehemiah 1:11', 'Nehemiah 4:14', 'Nehemiah 8:10'],
    outline: [[1, 7, 'Rebuilding the walls'], [8, 13, 'Renewing the people']],
    christ: 'A leader who left the palace to restore a broken city foreshadows Christ’s restoring work.' },
  est: { genre: 'History', author: 'Unknown', date: 'c. 460–350 BC', audience: 'Jews in the Persian empire',
    theme: 'God’s hidden providence — He is never named, yet He is everywhere at work.',
    summary: 'Esther, a Jewish orphan, becomes queen of Persia. When Haman plots to destroy the Jews, her cousin Mordecai urges her to act: “who knoweth whether thou art come to the kingdom for such a time as this?” She risks her life, and the people are saved — the origin of the feast of Purim.',
    keyVerses: ['Esther 4:14', 'Esther 4:16'],
    outline: [[1, 2, 'Esther becomes queen'], [3, 5, 'Haman’s plot'], [6, 10, 'The great reversal']],
    christ: 'A mediator who risks death to save her people points to Jesus, who gave His life to save us.' },
  job: { genre: 'Wisdom', author: 'Unknown', date: 'Uncertain; setting is patriarchal', audience: 'All who suffer',
    theme: 'Suffering and the sovereignty of God — trusting Him when life makes no sense.',
    summary: 'Job, a righteous man, loses his wealth, children and health. His friends insist he must have sinned; Job protests his innocence and longs to meet God. God finally speaks from the whirlwind, revealing His wisdom and power, and Job worships and is restored.',
    keyVerses: ['Job 1:21', 'Job 13:15', 'Job 19:25', 'Job 42:5'],
    outline: [[1, 2, 'Job’s testing'], [3, 31, 'Job and his friends'], [32, 37, 'Elihu'], [38, 42, 'God speaks; Job restored']],
    christ: 'Job’s cry “I know that my redeemer liveth” finds its answer in the risen Christ.' },
  psa: { genre: 'Poetry / Worship', author: 'David (73 psalms) plus Asaph, the sons of Korah, Solomon, Moses and others', date: 'c. 1440–450 BC', audience: 'Israel’s worship',
    theme: 'Prayer and praise for every season of life — joy, lament, confession and trust.',
    summary: 'The 150 Psalms are Israel’s prayer book and hymnal, arranged in five books. They teach God’s people to bring every emotion honestly before Him: thanksgiving, sorrow, anger, repentance, longing and exuberant praise.',
    keyVerses: ['Psalms 23:1', 'Psalms 46:1', 'Psalms 51:10', 'Psalms 119:105', 'Psalms 139:14'],
    outline: [[1, 41, 'Book I'], [42, 72, 'Book II'], [73, 89, 'Book III'], [90, 106, 'Book IV'], [107, 150, 'Book V']],
    christ: 'Jesus said the Psalms speak of Him (Luke 24:44); Psalms 2, 22, 110 and 118 are quoted of Him in the New Testament.' },
  pro: { genre: 'Wisdom', author: 'Mainly Solomon, with Agur and Lemuel', date: 'c. 950–700 BC', audience: 'Young people and all seeking wisdom',
    theme: 'Practical wisdom — “the fear of the LORD is the beginning of knowledge.”',
    summary: 'Proverbs is a collection of short sayings on wisdom for everyday life: speech, work, money, friendship, marriage, anger, pride and integrity. It contrasts the path of the wise with the path of the fool.',
    keyVerses: ['Proverbs 1:7', 'Proverbs 3:5-6', 'Proverbs 4:23', 'Proverbs 16:3'],
    outline: [[1, 9, 'Wisdom’s invitation'], [10, 29, 'Proverbs of Solomon'], [30, 31, 'Agur, Lemuel and the virtuous woman']],
    christ: 'Christ is “the wisdom of God” (1 Corinthians 1:24), in whom are hid all the treasures of wisdom (Colossians 2:3).' },
  ecc: { genre: 'Wisdom', author: '“The Preacher,” traditionally Solomon', date: 'c. 935 BC (traditional)', audience: 'Seekers of meaning',
    theme: 'Life “under the sun” without God is vanity; fear God and keep His commandments.',
    summary: 'Ecclesiastes honestly explores pleasure, work, wealth and wisdom and finds them all fleeting (“vanity of vanities”). It concludes that meaning is found in fearing God and enjoying His gifts with gratitude.',
    keyVerses: ['Ecclesiastes 3:1', 'Ecclesiastes 3:11', 'Ecclesiastes 12:13'],
    outline: [[1, 2, 'Everything is vanity'], [3, 5, 'A time for everything'], [6, 12, 'Wisdom for a fleeting life']],
    christ: 'Christ gives the eternal meaning Ecclesiastes searches for (John 10:10).' },
  sng: { genre: 'Poetry', author: 'Solomon (traditional)', date: 'c. 960 BC', audience: 'Israel',
    theme: 'The beauty and faithfulness of married love.',
    summary: 'The Song of Solomon is a love poem celebrating the delight, longing and commitment between a bride and groom. Many readers also see in it a picture of God’s love for His people.',
    keyVerses: ['Song of Solomon 2:4', 'Song of Solomon 8:6-7'],
    outline: [[1, 3, 'Courtship'], [4, 5, 'The wedding'], [6, 8, 'Growing love']],
    christ: 'The New Testament pictures Christ as the Bridegroom and the church as His bride (Ephesians 5:25-32).' },
  isa: { genre: 'Major Prophet', author: 'Isaiah son of Amoz', date: 'c. 740–680 BC', audience: 'Judah and Jerusalem',
    theme: 'Judgment and comfort — salvation through the Holy One of Israel and His Suffering Servant.',
    summary: 'Isaiah warns Judah of judgment for its sin, then turns to comfort, promising return from exile, the virgin-born Immanuel, the Prince of Peace, and the Suffering Servant who bears the sins of many. It ends with new heavens and a new earth.',
    keyVerses: ['Isaiah 6:8', 'Isaiah 9:6', 'Isaiah 40:31', 'Isaiah 53:5'],
    outline: [[1, 39, 'Judgment and the Assyrian crisis'], [40, 55, 'Comfort and the Servant'], [56, 66, 'Future glory']],
    christ: 'Isaiah is called “the fifth gospel”: Immanuel (7:14), the Child-King (9:6) and the Servant pierced for our transgressions (53:5).' },
  jer: { genre: 'Major Prophet', author: 'Jeremiah, recorded by Baruch', date: 'c. 627–580 BC', audience: 'Judah before and during the Babylonian exile',
    theme: 'Judgment for broken covenant, and the promise of a new covenant written on the heart.',
    summary: 'Jeremiah, “the weeping prophet,” warns Judah for forty years to repent before Babylon comes. He is rejected, imprisoned and grieves deeply, but also promises a future and a hope and a new covenant.',
    keyVerses: ['Jeremiah 1:5', 'Jeremiah 17:7-8', 'Jeremiah 29:11', 'Jeremiah 31:33'],
    outline: [[1, 1, 'Jeremiah’s call'], [2, 29, 'Warnings to Judah'], [30, 33, 'The book of comfort'], [34, 52, 'The fall of Jerusalem and the nations']],
    christ: 'Jesus inaugurates the new covenant in His blood (Luke 22:20; Hebrews 8:8-12).' },
  lam: { genre: 'Poetry / Lament', author: 'Jeremiah (traditional)', date: 'c. 586 BC', audience: 'Survivors of Jerusalem’s fall',
    theme: 'Grief over Jerusalem’s destruction — and hope in God’s new-every-morning mercies.',
    summary: 'Five acrostic poems mourn the destruction of Jerusalem. At the center of the sorrow stands a bright confession: the LORD’s compassions fail not; they are new every morning.',
    keyVerses: ['Lamentations 3:22-23', 'Lamentations 3:25'],
    outline: [[1, 2, 'Jerusalem’s ruin'], [3, 3, 'Hope in God’s mercy'], [4, 5, 'Prayer for restoration']],
    christ: 'Christ, the Man of Sorrows, carries the judgment Lamentations mourns.' },
  ezk: { genre: 'Major Prophet', author: 'Ezekiel, priest and prophet', date: 'c. 593–571 BC', audience: 'Exiles in Babylon',
    theme: 'The glory of God departs and returns; God will give His people a new heart and Spirit.',
    summary: 'Ezekiel sees visions of God’s glory, watches it leave the corrupt temple, and announces Jerusalem’s fall. Then he prophesies restoration: a new heart, the valley of dry bones coming to life, and a renewed temple.',
    keyVerses: ['Ezekiel 36:26', 'Ezekiel 37:5', 'Ezekiel 34:11'],
    outline: [[1, 3, 'Ezekiel’s call'], [4, 24, 'Judgment on Jerusalem'], [25, 32, 'Oracles against the nations'], [33, 48, 'Restoration']],
    christ: 'Jesus is the Good Shepherd promised in chapter 34 (John 10:11).' },
  dan: { genre: 'Prophecy / Apocalyptic', author: 'Daniel', date: 'c. 605–530 BC', audience: 'Jews in exile',
    theme: 'God rules over kings and kingdoms; stay faithful in a foreign land.',
    summary: 'Daniel and his friends stay faithful in Babylon — refusing the king’s food, surviving the fiery furnace and the lions’ den. Daniel’s visions reveal successive empires and the everlasting kingdom of the Son of man.',
    keyVerses: ['Daniel 2:44', 'Daniel 3:17-18', 'Daniel 6:10', 'Daniel 7:13-14'],
    outline: [[1, 6, 'Stories of faithfulness'], [7, 12, 'Visions of the kingdoms']],
    christ: 'Jesus called Himself the “Son of man” from Daniel 7:13 (Mark 14:62).' },
  hos: { genre: 'Minor Prophet', author: 'Hosea', date: 'c. 755–715 BC', audience: 'Northern Israel',
    theme: 'God’s faithful love for an unfaithful people.',
    summary: 'God tells Hosea to marry Gomer, who proves unfaithful — a living picture of Israel’s spiritual adultery. Yet Hosea buys her back, showing God’s relentless, redeeming love.',
    keyVerses: ['Hosea 6:6', 'Hosea 11:4', 'Hosea 14:4'],
    outline: [[1, 3, 'Hosea’s marriage'], [4, 14, 'God’s case and God’s love']],
    christ: 'Matthew 2:15 applies “out of Egypt have I called my son” (11:1) to Jesus.' },
  jol: { genre: 'Minor Prophet', author: 'Joel', date: 'Uncertain (possibly 9th or 5th century BC)', audience: 'Judah',
    theme: 'The day of the LORD — repent, and God will pour out His Spirit.',
    summary: 'A devastating locust plague becomes a warning of the coming day of the LORD. Joel calls for heartfelt repentance and promises restoration and the outpouring of God’s Spirit on all flesh.',
    keyVerses: ['Joel 2:13', 'Joel 2:25', 'Joel 2:28'],
    outline: [[1, 1, 'The locust plague'], [2, 2, 'Return to the LORD'], [3, 3, 'Judgment and blessing']],
    christ: 'Peter declared Joel 2:28 fulfilled at Pentecost (Acts 2:16-17).' },
  amo: { genre: 'Minor Prophet', author: 'Amos, a shepherd from Tekoa', date: 'c. 760 BC', audience: 'Prosperous northern Israel',
    theme: 'Justice — true worship cannot coexist with oppressing the poor.',
    summary: 'Amos condemns Israel’s luxury, corruption and empty religion. God desires justice to roll down like waters and righteousness like a mighty stream.',
    keyVerses: ['Amos 5:24', 'Amos 3:3'],
    outline: [[1, 2, 'Judgment on the nations'], [3, 6, 'Sermons to Israel'], [7, 9, 'Visions and restoration']],
    christ: 'The restored “tabernacle of David” (9:11) is applied to Christ’s church in Acts 15:16.' },
  oba: { genre: 'Minor Prophet', author: 'Obadiah', date: 'c. 586 BC', audience: 'Edom and Judah',
    theme: 'Pride goes before a fall — judgment on Edom.',
    summary: 'The Bible’s shortest Old Testament book announces judgment on Edom for gloating over Jerusalem’s fall, and promises that the kingdom shall be the LORD’s.',
    keyVerses: ['Obadiah 1:3', 'Obadiah 1:15'],
    outline: [[1, 1, 'Edom’s pride and judgment']],
    christ: 'The kingdom belongs to the LORD (v. 21) — fulfilled in Christ’s reign.' },
  jon: { genre: 'Minor Prophet', author: 'Jonah (traditional)', date: 'c. 760 BC', audience: 'Israel',
    theme: 'God’s compassion reaches even Israel’s enemies.',
    summary: 'Jonah flees God’s call to preach to Nineveh, is swallowed by a great fish, and finally obeys. Nineveh repents and God spares it — to Jonah’s anger. God’s last question exposes Jonah’s small heart and God’s great mercy.',
    keyVerses: ['Jonah 2:9', 'Jonah 4:2'],
    outline: [[1, 2, 'Jonah runs and is rescued'], [3, 4, 'Nineveh repents; Jonah sulks']],
    christ: 'Jesus pointed to “the sign of the prophet Jonas” — three days and nights before rising (Matthew 12:40).' },
  mic: { genre: 'Minor Prophet', author: 'Micah of Moresheth', date: 'c. 735–700 BC', audience: 'Judah and Israel',
    theme: 'Do justly, love mercy, walk humbly — and look for the ruler from Bethlehem.',
    summary: 'Micah condemns corrupt leaders and empty ritual, predicts judgment, and promises a ruler born in Bethlehem whose greatness reaches to the ends of the earth.',
    keyVerses: ['Micah 5:2', 'Micah 6:8', 'Micah 7:18'],
    outline: [[1, 3, 'Judgment'], [4, 5, 'Future hope and the Bethlehem ruler'], [6, 7, 'God’s case and mercy']],
    christ: 'Micah 5:2 names Bethlehem as the Messiah’s birthplace (Matthew 2:5-6).' },
  nah: { genre: 'Minor Prophet', author: 'Nahum', date: 'c. 660–612 BC', audience: 'Judah',
    theme: 'The LORD is slow to anger but will judge the cruel — Nineveh’s fall.',
    summary: 'About a century after Jonah, Nineveh has returned to violence. Nahum announces its downfall, comforting Judah that the LORD is a stronghold in the day of trouble.',
    keyVerses: ['Nahum 1:3', 'Nahum 1:7'],
    outline: [[1, 1, 'The LORD’s justice'], [2, 3, 'Nineveh’s fall']],
    christ: 'The “good tidings” of peace (1:15) anticipate the gospel.' },
  hab: { genre: 'Minor Prophet', author: 'Habakkuk', date: 'c. 610–600 BC', audience: 'Judah',
    theme: 'Wrestling honestly with God — “the just shall live by his faith.”',
    summary: 'Habakkuk asks why God tolerates evil, then why He would use wicked Babylon. God answers that the righteous live by faith. Habakkuk ends rejoicing in God even if the fig tree does not blossom.',
    keyVerses: ['Habakkuk 2:4', 'Habakkuk 3:17-18'],
    outline: [[1, 2, 'Questions and answers'], [3, 3, 'A prayer of trust']],
    christ: 'Paul builds the gospel of justification by faith on Habakkuk 2:4 (Romans 1:17).' },
  zep: { genre: 'Minor Prophet', author: 'Zephaniah', date: 'c. 640–620 BC', audience: 'Judah',
    theme: 'The day of the LORD — and God who rejoices over His people with singing.',
    summary: 'Zephaniah warns of a coming day of judgment, then promises a purified remnant and a God who quiets His people with His love.',
    keyVerses: ['Zephaniah 3:17'],
    outline: [[1, 1, 'Judgment on Judah'], [2, 2, 'Judgment on the nations'], [3, 3, 'Restoration and joy']],
    christ: 'The King of Israel in their midst (3:15) is fulfilled in Jesus.' },
  hag: { genre: 'Minor Prophet', author: 'Haggai', date: '520 BC', audience: 'The returned exiles',
    theme: 'Put God first — finish rebuilding His house.',
    summary: 'The returned exiles had stopped building the temple while paneling their own houses. Haggai calls them to “consider your ways” and promises that the latter glory of God’s house will be greater.',
    keyVerses: ['Haggai 1:5', 'Haggai 2:9'],
    outline: [[1, 1, 'Consider your ways'], [2, 2, 'Future glory']],
    christ: 'The greater glory of the temple is fulfilled when Christ comes to it.' },
  zec: { genre: 'Minor Prophet', author: 'Zechariah', date: 'c. 520–480 BC', audience: 'The returned exiles',
    theme: '“Not by might, nor by power, but by my spirit” — the coming King.',
    summary: 'Through night visions and prophecies, Zechariah encourages the rebuilding of the temple and foretells a humble King riding on a donkey, a pierced one mourned by His people, and the LORD reigning over all the earth.',
    keyVerses: ['Zechariah 4:6', 'Zechariah 9:9', 'Zechariah 12:10'],
    outline: [[1, 6, 'Night visions'], [7, 8, 'Questions about fasting'], [9, 14, 'The coming King']],
    christ: 'Jesus fulfilled 9:9 on Palm Sunday (Matthew 21:4-5); He is the one “pierced” (John 19:37).' },
  mal: { genre: 'Minor Prophet', author: 'Malachi', date: 'c. 430 BC', audience: 'Post-exilic Judah',
    theme: 'Return to Me with wholehearted worship — the messenger is coming.',
    summary: 'In a series of disputes, God confronts careless priests, broken marriages and withheld tithes. He promises a messenger to prepare the way and the Sun of righteousness rising with healing in His wings.',
    keyVerses: ['Malachi 3:1', 'Malachi 3:6', 'Malachi 3:10', 'Malachi 4:2'],
    outline: [[1, 2, 'God’s love and Israel’s careless worship'], [3, 4, 'The coming messenger']],
    christ: 'John the Baptist is the messenger (Matthew 11:10) preparing the way for Jesus.' },
  mat: { genre: 'Gospel', author: 'Matthew (Levi), the tax collector and apostle', date: 'c. AD 50–70', audience: 'Primarily Jewish readers',
    theme: 'Jesus is the promised Messiah-King who fulfils the Scriptures.',
    summary: 'Matthew presents Jesus as the Son of David and Son of Abraham, repeatedly showing how He fulfils prophecy. It contains the Sermon on the Mount, many parables of the kingdom, and ends with the Great Commission.',
    keyVerses: ['Matthew 5:3', 'Matthew 6:33', 'Matthew 11:28', 'Matthew 28:19-20'],
    outline: [[1, 4, 'Birth and preparation'], [5, 7, 'Sermon on the Mount'], [8, 20, 'Ministry and teaching'], [21, 28, 'Passion and resurrection']],
    christ: 'Jesus is Immanuel, “God with us” (1:23), present with His people to the end of the age (28:20).' },
  mrk: { genre: 'Gospel', author: 'John Mark, drawing on Peter’s preaching', date: 'c. AD 55–65', audience: 'Gentile (probably Roman) believers',
    theme: 'Jesus is the Servant who came to give His life a ransom for many.',
    summary: 'Mark is the shortest and most action-packed Gospel (“straightway” appears again and again). It emphasizes Jesus’ deeds and authority and devotes much of its length to His final week, death and resurrection.',
    keyVerses: ['Mark 1:15', 'Mark 8:34', 'Mark 10:45'],
    outline: [[1, 8, 'Who is Jesus?'], [8, 10, 'The way of the cross'], [11, 16, 'Jerusalem, death and resurrection']],
    christ: 'Jesus is the Son of God (1:1; 15:39) who serves and gives His life (10:45).' },
  luk: { genre: 'Gospel', author: 'Luke, the physician and companion of Paul', date: 'c. AD 60–62', audience: 'Theophilus and Gentile readers',
    theme: 'Jesus is the Savior who seeks and saves the lost.',
    summary: 'Luke offers a carefully researched account with special attention to the poor, women, outsiders, prayer and the Holy Spirit. It includes the parables of the Good Samaritan and the Prodigal Son, and the Emmaus road story.',
    keyVerses: ['Luke 2:11', 'Luke 4:18', 'Luke 15:7', 'Luke 19:10'],
    outline: [[1, 4, 'Birth and preparation'], [4, 9, 'Ministry in Galilee'], [9, 19, 'Journey to Jerusalem'], [19, 24, 'Jerusalem, cross and resurrection']],
    christ: 'The Son of man came to seek and to save that which was lost (19:10).' },
  jhn: { genre: 'Gospel', author: 'John, the beloved disciple', date: 'c. AD 85–95', audience: 'Believers and seekers',
    theme: 'Jesus is the Christ, the Son of God — believe and have life in His name.',
    summary: 'John was written “that ye might believe” (20:31). It presents seven signs, seven “I AM” sayings, the conversation with Nicodemus, the upper-room discourse and Jesus’ prayer in chapter 17, and the risen Christ restoring Peter.',
    keyVerses: ['John 1:1', 'John 1:14', 'John 3:16', 'John 14:6', 'John 20:31'],
    outline: [[1, 1, 'The Word made flesh'], [2, 12, 'The book of signs'], [13, 17, 'The upper room'], [18, 21, 'Death and resurrection']],
    christ: 'Jesus is the eternal Word, God made flesh, the Bread of life, Light of the world, Good Shepherd, Resurrection and the Life, the Way, and the true Vine.' },
  act: { genre: 'History', author: 'Luke', date: 'c. AD 62', audience: 'Theophilus',
    theme: 'The risen Jesus continues His work by the Holy Spirit through the church — from Jerusalem to the ends of the earth.',
    summary: 'Acts records the ascension, the outpouring of the Spirit at Pentecost, the growth of the Jerusalem church, Stephen’s martyrdom, Paul’s conversion and his missionary journeys, ending with Paul preaching in Rome.',
    keyVerses: ['Acts 1:8', 'Acts 2:38', 'Acts 4:12', 'Acts 16:31'],
    outline: [[1, 7, 'Witness in Jerusalem'], [8, 12, 'Judea and Samaria'], [13, 28, 'To the ends of the earth']],
    christ: 'Salvation is found in no other name (4:12).' },
  rom: { genre: 'Epistle (Paul)', author: 'Paul', date: 'c. AD 57', audience: 'The church in Rome',
    theme: 'The gospel is the power of God for salvation — righteousness by faith.',
    summary: 'Romans is Paul’s fullest explanation of the gospel: all have sinned; God justifies freely by grace through faith in Christ; believers are freed from sin and live by the Spirit; God remains faithful to Israel; and the gospel transforms everyday life.',
    keyVerses: ['Romans 1:16', 'Romans 3:23', 'Romans 5:8', 'Romans 6:23', 'Romans 8:28', 'Romans 12:1-2'],
    outline: [[1, 3, 'Sin and the need for righteousness'], [3, 5, 'Justification by faith'], [6, 8, 'New life in the Spirit'], [9, 11, 'God and Israel'], [12, 16, 'Living the gospel']],
    christ: 'God demonstrated His love in that while we were yet sinners, Christ died for us (5:8).' },
  '1co': { genre: 'Epistle (Paul)', author: 'Paul', date: 'c. AD 55', audience: 'The church in Corinth',
    theme: 'Correcting a divided, worldly church — and the way of love.',
    summary: 'Paul addresses divisions, immorality, lawsuits, marriage, idol food, worship, spiritual gifts and doubts about the resurrection. Chapter 13 is the great love chapter; chapter 15 the great resurrection chapter.',
    keyVerses: ['1 Corinthians 1:18', '1 Corinthians 10:13', '1 Corinthians 13:4-7', '1 Corinthians 15:3-4'],
    outline: [[1, 6, 'Divisions and disorders'], [7, 11, 'Questions on marriage, freedom and worship'], [12, 14, 'Spiritual gifts and love'], [15, 16, 'The resurrection']],
    christ: 'Christ crucified is the power and wisdom of God (1:23-24); His resurrection is the firstfruits of ours (15:20).' },
  '2co': { genre: 'Epistle (Paul)', author: 'Paul', date: 'c. AD 56', audience: 'The church in Corinth',
    theme: 'Strength in weakness — the ministry of a suffering servant.',
    summary: 'Paul’s most personal letter defends his ministry, describes God as the God of all comfort, encourages generous giving, and reveals his thorn in the flesh and God’s answer: “my grace is sufficient for thee.”',
    keyVerses: ['2 Corinthians 1:3-4', '2 Corinthians 4:17', '2 Corinthians 5:17', '2 Corinthians 12:9'],
    outline: [[1, 7, 'Paul’s ministry'], [8, 9, 'Generous giving'], [10, 13, 'Paul’s defense']],
    christ: 'In Christ we are a new creation, and He who knew no sin was made sin for us (5:17, 21).' },
  gal: { genre: 'Epistle (Paul)', author: 'Paul', date: 'c. AD 48–55', audience: 'Churches in Galatia',
    theme: 'Freedom in Christ — justified by faith, not by works of the law.',
    summary: 'Paul passionately defends the gospel of grace against teachers requiring circumcision. We are justified by faith in Christ, set free, and called to walk by the Spirit, producing the fruit of the Spirit.',
    keyVerses: ['Galatians 2:20', 'Galatians 5:1', 'Galatians 5:22-23', 'Galatians 6:9'],
    outline: [[1, 2, 'Paul’s gospel'], [3, 4, 'Faith versus the law'], [5, 6, 'Life in freedom']],
    christ: '“I am crucified with Christ… Christ liveth in me” (2:20).' },
  eph: { genre: 'Epistle (Paul)', author: 'Paul (from prison)', date: 'c. AD 60–62', audience: 'The church in Ephesus and the region',
    theme: 'Our riches in Christ and our walk in Christ — one new people.',
    summary: 'Chapters 1–3 celebrate every spiritual blessing in Christ: chosen, redeemed, saved by grace through faith, and united as Jew and Gentile. Chapters 4–6 call believers to live worthy of that calling in the church, the home, and in spiritual warfare with the armor of God.',
    keyVerses: ['Ephesians 2:8-9', 'Ephesians 2:10', 'Ephesians 4:32', 'Ephesians 6:10-11'],
    outline: [[1, 3, 'Who we are in Christ'], [4, 6, 'How we walk in Christ']],
    christ: 'All things are gathered together in Christ, who is head over all things to the church (1:10, 22).' },
  php: { genre: 'Epistle (Paul)', author: 'Paul (from prison)', date: 'c. AD 61', audience: 'The church in Philippi',
    theme: 'Joy in Christ in every circumstance.',
    summary: 'Written from chains, Philippians overflows with joy. Paul holds up Christ’s humility (2:5-11) as our pattern, counts all things loss to know Christ, and teaches prayerful contentment: “I can do all things through Christ.”',
    keyVerses: ['Philippians 1:21', 'Philippians 2:5-8', 'Philippians 4:6-7', 'Philippians 4:13'],
    outline: [[1, 1, 'Joy in suffering'], [2, 2, 'Joy in serving'], [3, 3, 'Joy in knowing Christ'], [4, 4, 'Joy and peace in all things']],
    christ: 'Christ humbled Himself to the cross and is exalted with the name above every name (2:8-11).' },
  col: { genre: 'Epistle (Paul)', author: 'Paul (from prison)', date: 'c. AD 60–62', audience: 'The church in Colossae',
    theme: 'The supremacy and sufficiency of Christ.',
    summary: 'Facing teaching that added philosophy and rules to Christ, Paul declares Christ the image of the invisible God, Creator and head of the church, in whom the fullness of God dwells. Believers are complete in Him and should set their minds on things above.',
    keyVerses: ['Colossians 1:15-17', 'Colossians 2:9-10', 'Colossians 3:2', 'Colossians 3:23'],
    outline: [[1, 2, 'Christ is supreme'], [3, 4, 'Living in Christ']],
    christ: 'In Him dwells all the fullness of the Godhead bodily (2:9).' },
  '1th': { genre: 'Epistle (Paul)', author: 'Paul', date: 'c. AD 50–51', audience: 'The young church in Thessalonica',
    theme: 'Faith, hope and love while waiting for the Lord’s return.',
    summary: 'Paul commends the new believers, encourages holy living, and comforts those grieving with the hope of Christ’s return and the resurrection.',
    keyVerses: ['1 Thessalonians 4:16-17', '1 Thessalonians 5:16-18'],
    outline: [[1, 3, 'Thanksgiving and Paul’s ministry'], [4, 5, 'Holy living and the Lord’s coming']],
    christ: 'The Lord Himself will descend from heaven (4:16).' },
  '2th': { genre: 'Epistle (Paul)', author: 'Paul', date: 'c. AD 51', audience: 'The church in Thessalonica',
    theme: 'Stand firm and keep working until the day of the Lord.',
    summary: 'Paul corrects confusion that the day of the Lord had already come, encourages perseverance under persecution, and rebukes idleness.',
    keyVerses: ['2 Thessalonians 3:3', '2 Thessalonians 3:13'],
    outline: [[1, 1, 'Encouragement in persecution'], [2, 2, 'The day of the Lord'], [3, 3, 'Work and prayer']],
    christ: 'The Lord is faithful to establish and keep you (3:3).' },
  '1ti': { genre: 'Pastoral Epistle', author: 'Paul', date: 'c. AD 62–64', audience: 'Timothy, leading the church in Ephesus',
    theme: 'Order and godliness in the household of God.',
    summary: 'Paul instructs young Timothy on sound doctrine, prayer, qualifications for overseers and deacons, caring for widows, and the danger of loving money. He urges him to fight the good fight of faith.',
    keyVerses: ['1 Timothy 1:15', '1 Timothy 2:5', '1 Timothy 4:12', '1 Timothy 6:6'],
    outline: [[1, 1, 'Sound doctrine'], [2, 3, 'Worship and leaders'], [4, 6, 'Timothy’s ministry']],
    christ: 'There is one mediator between God and men, the man Christ Jesus (2:5).' },
  '2ti': { genre: 'Pastoral Epistle', author: 'Paul (his last letter)', date: 'c. AD 66–67', audience: 'Timothy',
    theme: 'Guard the gospel and finish the race.',
    summary: 'From a Roman prison facing death, Paul urges Timothy to be strong, suffer hardship as a good soldier, hold to Scripture which is God-breathed, and preach the word. “I have fought a good fight, I have finished my course, I have kept the faith.”',
    keyVerses: ['2 Timothy 1:7', '2 Timothy 2:15', '2 Timothy 3:16-17', '2 Timothy 4:7'],
    outline: [[1, 2, 'Be strong and faithful'], [3, 4, 'Preach the word']],
    christ: 'Christ abolished death and brought life and immortality to light (1:10).' },
  tit: { genre: 'Pastoral Epistle', author: 'Paul', date: 'c. AD 63–65', audience: 'Titus, in Crete',
    theme: 'Grace that teaches godly living.',
    summary: 'Paul tells Titus to appoint elders and teach sound doctrine, showing how the grace of God trains believers to live soberly, righteously and godly.',
    keyVerses: ['Titus 2:11-12', 'Titus 3:5'],
    outline: [[1, 1, 'Elders'], [2, 2, 'Sound teaching for every age'], [3, 3, 'Saved by mercy']],
    christ: 'He saved us not by works of righteousness but according to His mercy (3:5).' },
  phm: { genre: 'Epistle (Paul)', author: 'Paul (from prison)', date: 'c. AD 60–62', audience: 'Philemon',
    theme: 'Forgiveness and reconciliation in Christ.',
    summary: 'Paul appeals to Philemon to welcome back his runaway slave Onesimus — now a believer — “not now as a servant, but above a servant, a brother beloved,” offering to pay any debt himself.',
    keyVerses: ['Philemon 1:16', 'Philemon 1:18'],
    outline: [[1, 1, 'An appeal for Onesimus']],
    christ: 'Paul’s “put that on mine account” mirrors Christ taking our debt.' },
  heb: { genre: 'Epistle', author: 'Unknown (Paul, Barnabas and Apollos have been suggested)', date: 'c. AD 60–69', audience: 'Jewish Christians tempted to turn back',
    theme: 'Jesus is better — better than angels, Moses and the old priesthood and sacrifices.',
    summary: 'Hebrews shows Jesus as superior to every Old Testament institution: the final High Priest, the perfect sacrifice and mediator of a better covenant. It urges perseverance, recounts the heroes of faith (chapter 11), and calls us to run with our eyes on Jesus.',
    keyVerses: ['Hebrews 4:12', 'Hebrews 4:15-16', 'Hebrews 11:1', 'Hebrews 12:1-2', 'Hebrews 13:8'],
    outline: [[1, 4, 'Jesus is superior'], [5, 10, 'The better priesthood and sacrifice'], [11, 13, 'Faith and endurance']],
    christ: 'Jesus Christ the same yesterday, and to day, and for ever (13:8).' },
  jas: { genre: 'Epistle', author: 'James, the brother of Jesus', date: 'c. AD 45–49', audience: 'Jewish believers scattered abroad',
    theme: 'Genuine faith works — trials, wisdom, the tongue and caring for the poor.',
    summary: 'James is practical wisdom for Christians: count trials as joy, ask God for wisdom, be doers of the word, show no favoritism, tame the tongue, humble yourselves, and pray in faith. Faith without works is dead.',
    keyVerses: ['James 1:2-3', 'James 1:5', 'James 1:22', 'James 2:17', 'James 4:8'],
    outline: [[1, 1, 'Trials and the word'], [2, 2, 'Faith that works'], [3, 4, 'The tongue and humility'], [5, 5, 'Patience and prayer']],
    christ: 'The Lord’s coming draws near; be patient (5:8).' },
  '1pe': { genre: 'Epistle', author: 'Peter', date: 'c. AD 62–64', audience: 'Believers scattered and suffering',
    theme: 'Living hope in the middle of suffering.',
    summary: 'Peter reminds suffering Christians of their living hope through the resurrection, their identity as a chosen people and royal priesthood, and how to live well and suffer well, casting all their care on God.',
    keyVerses: ['1 Peter 1:3', '1 Peter 2:9', '1 Peter 3:15', '1 Peter 5:7'],
    outline: [[1, 2, 'Our salvation and identity'], [2, 4, 'Living as exiles'], [4, 5, 'Suffering and shepherding']],
    christ: 'Christ also suffered for us, leaving us an example (2:21-24).' },
  '2pe': { genre: 'Epistle', author: 'Peter', date: 'c. AD 64–68', audience: 'Believers',
    theme: 'Grow in grace and beware false teachers — the Lord will come.',
    summary: 'Peter urges growth in virtue, warns against false teachers, and explains that the Lord is not slow but patient, not willing that any should perish.',
    keyVerses: ['2 Peter 1:3', '2 Peter 3:9', '2 Peter 3:18'],
    outline: [[1, 1, 'Growing in grace'], [2, 2, 'False teachers'], [3, 3, 'The day of the Lord']],
    christ: 'Grow in the grace and knowledge of our Lord and Saviour Jesus Christ (3:18).' },
  '1jn': { genre: 'Epistle', author: 'John the apostle', date: 'c. AD 85–95', audience: 'Churches in Asia Minor',
    theme: 'Assurance — know that you have eternal life; God is light and God is love.',
    summary: 'John gives tests of genuine faith — walking in the light, obeying God, loving one another, and believing Jesus came in the flesh — so believers may know they have eternal life.',
    keyVerses: ['1 John 1:9', '1 John 3:1', '1 John 4:8', '1 John 4:19', '1 John 5:13'],
    outline: [[1, 2, 'Walking in the light'], [3, 4, 'Living as God’s children in love'], [5, 5, 'Assurance of eternal life']],
    christ: 'Jesus Christ the righteous is our advocate with the Father (2:1).' },
  '2jn': { genre: 'Epistle', author: 'John (“the elder”)', date: 'c. AD 85–95', audience: '“The elect lady and her children”',
    theme: 'Walk in truth and love; do not welcome false teachers.',
    summary: 'A brief letter urging believers to love one another and to guard against deceivers who deny Christ came in the flesh.',
    keyVerses: ['2 John 1:6'],
    outline: [[1, 1, 'Truth and love']],
    christ: 'Confessing Jesus Christ come in the flesh is the test of truth (v. 7).' },
  '3jn': { genre: 'Epistle', author: 'John (“the elder”)', date: 'c. AD 85–95', audience: 'Gaius',
    theme: 'Hospitality to faithful workers.',
    summary: 'John commends Gaius for hospitality, rebukes the domineering Diotrephes, and praises Demetrius.',
    keyVerses: ['3 John 1:2', '3 John 1:4'],
    outline: [[1, 1, 'Walking in truth']],
    christ: 'Workers go out “for his name’s sake” (v. 7).' },
  jud: { genre: 'Epistle', author: 'Jude, brother of James', date: 'c. AD 65–80', audience: 'Believers',
    theme: 'Contend for the faith — and rest in the God who keeps you from falling.',
    summary: 'Jude warns about ungodly people slipping into the church and urges believers to build themselves up in faith. It closes with one of the Bible’s great doxologies.',
    keyVerses: ['Jude 1:3', 'Jude 1:24-25'],
    outline: [[1, 1, 'Contend for the faith']],
    christ: 'He is able to keep you from falling (v. 24).' },
  rev: { genre: 'Prophecy / Apocalyptic', author: 'John the apostle (traditional)', date: 'c. AD 95', audience: 'Seven churches in Asia',
    theme: 'Jesus wins — the Lamb who was slain reigns, and God will make all things new.',
    summary: 'Revelation opens with letters from the risen Christ to seven churches, then visions of heaven’s throne, the Lamb who opens the sealed scroll, judgments, the defeat of evil, and finally the new heaven and new earth where God wipes away every tear.',
    keyVerses: ['Revelation 1:8', 'Revelation 3:20', 'Revelation 21:4', 'Revelation 22:20'],
    outline: [[1, 3, 'Christ and the seven churches'], [4, 5, 'The throne and the Lamb'], [6, 20, 'Judgments and victory'], [21, 22, 'All things new']],
    christ: 'Jesus is the Alpha and Omega, the Lamb slain, and King of kings and Lord of lords (19:16).' },
};
