// Common factual / doctrinal questions. `patterns` are case-insensitive
// regular expressions tested against the question.
export const FAQ = [
  { id: 'books_count', patterns: ['how many books', 'number of books', 'books (are )?in the bible'],
    title: 'How many books are in the Bible?',
    answer: 'The Protestant Bible has 66 books: 39 in the Old Testament and 27 in the New Testament. They were written by about 40 authors over roughly 1,500 years, in Hebrew, Aramaic and Greek. Catholic and Orthodox Bibles also include several additional books (the deuterocanonical books, such as Tobit and 1–2 Maccabees).\n\nThe Old Testament is usually grouped as Law (Genesis–Deuteronomy), History (Joshua–Esther), Wisdom and Poetry (Job–Song of Solomon) and Prophets (Isaiah–Malachi). The New Testament contains the four Gospels, Acts, 21 letters and Revelation.',
    refs: ['2 Timothy 3:16', '2 Peter 1:21'] },
  { id: 'trinity', patterns: ['trinity', 'triune', 'three in one', 'father,? son,? and (the )?holy'],
    title: 'What is the Trinity?',
    answer: 'The Trinity is the Christian teaching that there is one God who eternally exists as three distinct Persons — the Father, the Son and the Holy Spirit — each fully God, yet not three gods. The word “Trinity” is not in the Bible, but the truth is drawn from many passages.\n\nScripture insists there is only one God (Deuteronomy 6:4). It calls the Father God, the Son God (John 1:1; John 20:28) and the Holy Spirit God (Acts 5:3-4). All three appear together at Jesus’ baptism, and believers are baptized into the one “name” of Father, Son and Holy Spirit.',
    refs: ['Deuteronomy 6:4', 'Matthew 3:16-17', 'Matthew 28:19', 'John 1:1', '2 Corinthians 13:14'] },
  { id: 'ten_commandments', patterns: ['ten commandments', '10 commandments', 'decalogue'],
    title: 'What are the Ten Commandments?',
    answer: 'God gave the Ten Commandments to Israel at Mount Sinai (Exodus 20; repeated in Deuteronomy 5):\n\n1. You shall have no other gods before Me.\n2. You shall not make or worship idols.\n3. You shall not take the LORD’s name in vain.\n4. Remember the sabbath day to keep it holy.\n5. Honor your father and mother.\n6. You shall not murder.\n7. You shall not commit adultery.\n8. You shall not steal.\n9. You shall not bear false witness.\n10. You shall not covet.\n\nJesus summarized them in two great commandments: love God with all your heart, soul and mind, and love your neighbor as yourself.',
    refs: ['Exodus 20:2-17', 'Matthew 22:37-40'] },
  { id: 'fruit_spirit', patterns: ['fruit of the spirit', 'fruits of the spirit'],
    title: 'What is the fruit of the Spirit?',
    answer: 'Galatians 5:22-23 lists the fruit of the Spirit: love, joy, peace, longsuffering (patience), gentleness (kindness), goodness, faith (faithfulness), meekness (gentleness) and temperance (self-control). Paul calls it “fruit” (singular) — one character of Christ growing in a believer as they walk by the Spirit, in contrast to the “works of the flesh.”',
    refs: ['Galatians 5:22-23', 'Galatians 5:16', 'John 15:5'] },
  { id: 'beatitudes', patterns: ['beatitude', 'blessed are the'],
    title: 'What are the Beatitudes?',
    answer: 'The Beatitudes open Jesus’ Sermon on the Mount (Matthew 5:3-12). Jesus pronounces God’s blessing on the poor in spirit, those who mourn, the meek, those who hunger and thirst for righteousness, the merciful, the pure in heart, the peacemakers, and those persecuted for righteousness’ sake. They describe the upside-down character of people in God’s kingdom.',
    refs: ['Matthew 5:3-12', 'Luke 6:20-23'] },
  { id: 'lords_prayer', patterns: ["lord'?s prayer", 'our father which art', 'our father who art'],
    title: 'What is the Lord’s Prayer?',
    answer: 'The Lord’s Prayer is the model Jesus gave His disciples when they asked Him to teach them to pray (Matthew 6:9-13; Luke 11:2-4). It begins with God — His name hallowed, His kingdom come, His will done — and then brings our needs: daily bread, forgiveness as we forgive others, and deliverance from temptation and evil.',
    refs: ['Matthew 6:9-13', 'Luke 11:1-4'] },
  { id: 'armor', patterns: ['armou?r of god', 'whole armou?r'],
    title: 'What is the armor of God?',
    answer: 'In Ephesians 6:10-18, Paul describes the spiritual armor God provides for standing against the devil: the belt of truth, the breastplate of righteousness, feet shod with the gospel of peace, the shield of faith, the helmet of salvation, and the sword of the Spirit, which is the word of God — all worn with prayer in the Spirit.',
    refs: ['Ephesians 6:10-18'] },
  { id: 'disciples', patterns: ['12 disciples', 'twelve disciples', '12 apostles', 'twelve apostles', 'names of the disciples', 'who were the disciples'],
    title: 'Who were the twelve disciples?',
    answer: 'Jesus chose twelve apostles: Simon Peter, Andrew his brother, James and John (sons of Zebedee), Philip, Bartholomew, Thomas, Matthew the tax collector, James son of Alphaeus, Thaddaeus (also called Judas son of James), Simon the Zealot, and Judas Iscariot, who betrayed Him. After Judas’ death, Matthias was chosen to replace him.',
    refs: ['Matthew 10:2-4', 'Luke 6:13-16', 'Acts 1:26'] },
  { id: 'who_wrote_bible', patterns: ['who wrote the bible', 'who wrote bible', 'authors? of the bible'],
    title: 'Who wrote the Bible?',
    answer: 'About 40 human authors wrote the Bible over roughly 1,500 years — kings, shepherds, prophets, a tax collector, a doctor, fishermen and a former Pharisee. Moses is traditionally credited with the first five books; David with many psalms; Solomon with much of Proverbs; prophets like Isaiah and Jeremiah with their books; and in the New Testament, Matthew, Mark, Luke, John, Paul, Peter, James and Jude. Christians believe that behind the human authors is one divine Author: “all scripture is given by inspiration of God.”',
    refs: ['2 Timothy 3:16-17', '2 Peter 1:20-21'] },
  { id: 'jesus_god', patterns: ['is jesus god', 'jesus (is|was) god', 'divinity of (jesus|christ)', 'was jesus just a'],
    title: 'Is Jesus God?',
    answer: 'The New Testament teaches that Jesus is fully God and fully man. John opens: “the Word was God… and the Word was made flesh.” Jesus forgave sins, accepted worship, and said “before Abraham was, I am,” using God’s own name — which is why His hearers tried to stone Him. Thomas confessed Him as “My Lord and my God,” and Paul calls Him the one in whom “dwelleth all the fulness of the Godhead bodily.”',
    refs: ['John 1:1', 'John 1:14', 'John 8:58', 'John 20:28', 'Colossians 2:9', 'Philippians 2:5-7'] },
  { id: 'why_jesus_die', patterns: ['why did jesus (have to )?die', 'why (was|did) jesus crucified', 'purpose of the cross', 'why the cross'],
    title: 'Why did Jesus die?',
    answer: 'Scripture says Jesus died as a substitute for sinners. All have sinned, and the wages of sin is death; but Christ “bare our sins in his own body on the tree.” Isaiah foretold that the Servant would be wounded for our transgressions. At the cross God’s justice and mercy meet: sin is truly paid for, and sinners are freely forgiven. Jesus said He came to give His life “a ransom for many,” and His resurrection proves the payment was accepted.',
    refs: ['Isaiah 53:5-6', 'Mark 10:45', 'Romans 5:8', '2 Corinthians 5:21', '1 Peter 2:24', '1 Peter 3:18'] },
  { id: 'resurrection', patterns: ['did jesus rise', 'resurrection of jesus', 'empty tomb', 'jesus rose', 'evidence for the resurrection'],
    title: 'Did Jesus really rise from the dead?',
    answer: 'All four Gospels report the empty tomb and appearances of the risen Jesus. Paul, writing around AD 55, passes on an early creed listing appearances to Peter, the twelve, more than 500 people at once (most still alive to be questioned), James and himself. The disciples went from hiding in fear to boldly preaching — many suffering for it. Paul says Christianity stands or falls on this: “if Christ be not raised, your faith is vain.”',
    refs: ['1 Corinthians 15:3-8', '1 Corinthians 15:14', '1 Corinthians 15:20', 'Luke 24:36-43', 'Acts 2:32'] },
  { id: 'sin_definition', patterns: ['what is sin', 'definition of sin', 'meaning of sin'],
    title: 'What is sin?',
    answer: 'Sin is any failure to love and obey God — in thought, word, deed or attitude. The Bible uses words meaning “missing the mark,” “transgression” (crossing a line) and “iniquity” (crookedness). 1 John defines it as lawlessness. Sin is not just bad actions but a condition of the heart inherited since Adam, which is why we need a Savior, not just self-improvement.',
    refs: ['1 John 3:4', 'Romans 3:23', 'James 4:17', 'Romans 5:12', 'Jeremiah 17:9'] },
  { id: 'unforgivable', patterns: ['unforgivable sin', 'unpardonable', 'blasphemy (against|of) the (holy )?(spirit|ghost)'],
    title: 'What is the unforgivable sin?',
    answer: 'Jesus warned about “blasphemy against the Holy Ghost” after religious leaders attributed His Spirit-empowered miracles to Satan (Mark 3:22-30). Most teachers understand it as a settled, persistent rejection of the Spirit’s witness to Christ — not a single careless word. Someone worried that they have committed it is showing the very sensitivity to God that the hardened heart lacks. Whoever comes to Jesus He will not cast out.',
    refs: ['Mark 3:28-30', 'Matthew 12:31-32', 'John 6:37', '1 John 1:9'] },
  { id: 'tithe', patterns: ['tithe', 'tithing', '10 percent', 'ten percent'],
    title: 'What does the Bible say about tithing?',
    answer: 'A tithe means a tenth. Abraham gave a tenth to Melchizedek, and the Law of Moses required tithes to support the Levites and the poor. Malachi rebuked Israel for withholding tithes. In the New Testament, Jesus affirmed generous giving while emphasizing justice and mercy, and Paul teaches that each should give as purposed in the heart — regularly, proportionally and cheerfully. Many Christians see the tithe as a helpful starting point for generosity.',
    refs: ['Genesis 14:18-20', 'Malachi 3:10', 'Matthew 23:23', '1 Corinthians 16:2', '2 Corinthians 9:7'] },
  { id: 'rapture', patterns: ['rapture', 'second coming', 'return of (jesus|christ)', 'end times', 'end of the world', 'last days'],
    title: 'What does the Bible say about Jesus’ return?',
    answer: 'The New Testament clearly teaches that Jesus will return personally and visibly, raise the dead, judge the world and make all things new. Paul describes believers being “caught up” to meet the Lord. Christians differ on the order and timing of end-time events, but Jesus said no one knows the day or hour — so the call is to be watchful, faithful and hopeful.',
    refs: ['Acts 1:11', '1 Thessalonians 4:16-17', 'Matthew 24:36', 'Matthew 24:42-44', 'Revelation 22:20'] },
  { id: 'old_vs_new', patterns: ['difference between (the )?old and new testament', 'old testament vs', 'what is the old testament', 'what is the new testament'],
    title: 'What is the difference between the Old and New Testaments?',
    answer: 'The Old Testament (39 books) records creation, God’s covenant with Israel, the Law, Israel’s history, wisdom literature and the prophets, written mostly in Hebrew before Christ. The New Testament (27 books) records the life, death and resurrection of Jesus, the growth of the early church, apostolic letters and Revelation, written in Greek in the first century. “Testament” means covenant: the Old points forward to Christ, and the New announces the new covenant in His blood.',
    refs: ['Jeremiah 31:31-33', 'Luke 22:20', 'Luke 24:27', 'Hebrews 8:6'] },
  { id: 'gospel_meaning', patterns: ['what is the gospel', 'meaning of gospel', 'what does gospel mean'],
    title: 'What is the gospel?',
    answer: '“Gospel” means good news. Paul summarizes it as the message “of first importance”: Christ died for our sins according to the Scriptures, was buried, and rose again the third day. God offers forgiveness and eternal life as a free gift to everyone who repents and believes in Jesus.',
    refs: ['1 Corinthians 15:1-4', 'Romans 1:16', 'Mark 1:15', 'John 3:16'] },
  { id: 'born_again', patterns: ['born again', 'new birth', 'regenerat'],
    title: 'What does “born again” mean?',
    answer: 'Jesus told Nicodemus, “Except a man be born again, he cannot see the kingdom of God.” Being born again (or “born from above”) is the new spiritual life God gives by His Spirit when a person trusts Christ. It is not self-improvement but a new start: “if any man be in Christ, he is a new creature.”',
    refs: ['John 3:3-7', 'John 3:16', '2 Corinthians 5:17', '1 Peter 1:23', 'Titus 3:5'] },
  { id: 'heaven_how', patterns: ['how (do i|to|can i) (get|go) to heaven', 'how to be saved', 'how can i be saved', 'how do i become a christian', 'how to become a christian'],
    title: 'How can I be saved?',
    answer: 'The Bible’s answer is simple and wonderful: salvation is a gift received by faith in Jesus Christ, not earned by good works. Admit you are a sinner who needs God’s forgiveness; believe that Jesus died for your sins and rose again; and receive Him as your Lord and Savior, turning from sin to follow Him. “Whosoever shall call upon the name of the Lord shall be saved.”',
    refs: ['Romans 3:23', 'Romans 6:23', 'Ephesians 2:8-9', 'Romans 10:9-10', 'Romans 10:13', 'John 1:12'] },
  { id: 'longest_book', patterns: ['longest book', 'shortest book', 'longest chapter', 'shortest chapter', 'shortest verse', 'longest verse', 'middle (verse|chapter)'],
    title: 'Bible records: longest and shortest',
    answer: '• Longest book by chapters: Psalms (150 chapters).\n• Longest chapter: Psalm 119 (176 verses).\n• Shortest chapter: Psalm 117 (2 verses).\n• Shortest verse (KJV): John 11:35, “Jesus wept.”\n• Longest verse (KJV): Esther 8:9.\n• Shortest books: 2 John and 3 John (one chapter each, among the fewest verses).',
    refs: ['Psalms 117:1-2', 'John 11:35'] },
  { id: 'first_last', patterns: ['first (verse|book|words) (of|in) the bible', 'last (verse|book|words) (of|in) the bible'],
    title: 'The first and last words of the Bible',
    answer: 'The Bible opens in Genesis 1:1: “In the beginning God created the heaven and the earth.” It closes in Revelation 22:21: “The grace of our Lord Jesus Christ be with you all. Amen.” From creation to new creation, from “In the beginning God” to “the grace of our Lord Jesus.”',
    refs: ['Genesis 1:1', 'Revelation 22:21'] },
  { id: 'kjv', patterns: ['king james', 'kjv', 'which (bible )?translation', 'best translation'],
    title: 'About Bible translations (and the KJV)',
    answer: 'The King James Version (1611) was commissioned by King James I of England and translated by about 47 scholars. It shaped the English language for centuries. Modern translations aim either for word-for-word accuracy (KJV, NKJV, ESV, NASB), thought-for-thought readability (NIV, NLT), or a balance. In this app you can switch between the KJV, the World English Bible (WEB), the American Standard Version (ASV) and the Bible in Basic English (BBE) using the version badge.',
    refs: ['Psalms 119:105', '2 Timothy 3:16'] },
  { id: 'god_exist', patterns: ['does god exist', 'is god real', 'prove god', 'proof of god', 'evidence (for|of) god'],
    title: 'Is God real?',
    answer: 'The Bible does not argue for God’s existence so much as assume it — “In the beginning God.” Yet it points to evidence all around us: “The heavens declare the glory of God.” Paul says God’s invisible qualities are clearly seen through what has been made, and that God has given witness through conscience, providence and, above all, Jesus, who claimed to reveal the Father and rose from the dead. The invitation is personal: “O taste and see that the LORD is good.”',
    refs: ['Psalms 19:1-2', 'Romans 1:20', 'Acts 17:24-28', 'John 14:9', 'Psalms 34:8'] },
  { id: 'holy_communion', patterns: ['communion', "lord'?s supper", 'eucharist', 'breaking (of )?bread'],
    title: 'What is Communion (the Lord’s Supper)?',
    answer: 'On the night He was betrayed, Jesus took bread and the cup and told His disciples to do this “in remembrance of me.” The bread represents His body given for us and the cup the new covenant in His blood. Paul teaches that each time believers share it they proclaim the Lord’s death until He comes, and should take it with self-examination and reverence.',
    refs: ['Luke 22:19-20', '1 Corinthians 11:23-28'] },
  { id: 'angels', patterns: ['angels?', 'guardian angel'],
    title: 'What does the Bible say about angels?',
    answer: 'Angels are created spiritual beings who worship God and serve as His messengers. Gabriel announced the births of John the Baptist and Jesus; Michael is called an archangel. Hebrews calls angels “ministering spirits, sent forth to minister for them who shall be heirs of salvation.” Scripture forbids worshipping them — they point to God.',
    refs: ['Hebrews 1:14', 'Psalms 91:11', 'Luke 1:26-27', 'Revelation 22:8-9'] },
  { id: 'satan', patterns: ['satan', 'the devil', 'lucifer', 'demons?'],
    title: 'What does the Bible say about Satan?',
    answer: 'Satan (meaning “adversary”), also called the devil, is a real, personal spiritual enemy of God and His people — a liar and accuser who tempts and deceives. But he is a defeated foe: Jesus came to destroy the works of the devil, disarmed the powers at the cross, and will finally cast him down. Believers are told to resist him, steadfast in faith, and he will flee.',
    refs: ['John 8:44', '1 Peter 5:8-9', 'James 4:7', '1 John 3:8', 'Colossians 2:15', 'Revelation 20:10'] },
  { id: 'love_neighbor', patterns: ['greatest commandment', 'most important commandment', 'love (your|thy) neighbou?r'],
    title: 'What is the greatest commandment?',
    answer: 'When asked which commandment is greatest, Jesus answered: “Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment. And the second is like unto it, Thou shalt love thy neighbour as thyself.” On these two hang all the law and the prophets. In the parable of the Good Samaritan He showed that our neighbor is anyone in need.',
    refs: ['Matthew 22:36-40', 'Deuteronomy 6:5', 'Leviticus 19:18', 'Luke 10:29-37'] },
  { id: 'prodigal', patterns: ['prodigal', 'lost son'], title: 'The parable of the prodigal son',
    answer: 'In Luke 15:11-32 Jesus tells of a younger son who demands his inheritance, wastes it in “riotous living,” and ends up feeding pigs. Coming to himself, he returns home to ask to be a hired servant — but his father sees him from far off, runs to him, embraces him, and throws a feast. The resentful older brother refuses to celebrate.\nJesus told the story (with the lost sheep and lost coin) to religious leaders who grumbled that He welcomed sinners. It reveals a Father who welcomes the repentant with extravagant grace — and challenges the self-righteous “older brothers” to join the celebration.',
    refs: ['Luke 15:20-24', 'Luke 15:31-32', 'Luke 15:1-2'] },
  { id: 'samaritan', patterns: ['good samaritan', 'samaritan', 'who is my neighbou?r'], title: 'The parable of the Good Samaritan',
    answer: 'When a lawyer asked “who is my neighbour?”, Jesus told of a man beaten by robbers on the road from Jerusalem to Jericho. A priest and a Levite passed by, but a Samaritan — from a people despised by Jews — had compassion, bandaged his wounds, took him to an inn and paid for his care.\nJesus turned the question around: not “who qualifies as my neighbour?” but “will you be a neighbour?” — and said, “Go, and do thou likewise.”',
    refs: ['Luke 10:29-37'] },
  { id: 'sower', patterns: ['parable of the sower', 'sower', 'seed on (stony|good) ground'], title: 'The parable of the sower',
    answer: 'Jesus describes a farmer scattering seed on four kinds of ground: the wayside (birds eat it), stony ground (it springs up but withers), among thorns (it is choked), and good ground (it bears fruit thirty, sixty or a hundredfold).\nJesus explained that the seed is the word of God and the soils are hearts: some hear without understanding, some fall away under trouble, some are choked by cares and riches, and some hear, understand and bear fruit.',
    refs: ['Matthew 13:3-9', 'Matthew 13:18-23'] },
  { id: 'talents', patterns: ['parable of the talents', 'talents'], title: 'The parable of the talents',
    answer: 'A master entrusts his servants with five, two and one talents (large sums of money). The first two trade and double what they received; the third buries his. On return, the master commends the faithful servants — “Well done, thou good and faithful servant” — and rebukes the one who hid his talent out of fear.\nThe parable teaches faithful stewardship of everything God entrusts to us while we await Christ’s return.',
    refs: ['Matthew 25:14-30'] },
  { id: 'creation', patterns: ['creation', 'how (was|did god create) the world', 'seven days', '6 days', 'six days'], title: 'Creation in Genesis 1–2',
    answer: 'Genesis 1 describes God creating by His word over six days — light; sky and waters; land, seas and plants; sun, moon and stars; sea creatures and birds; land animals and humanity in His image — and resting on the seventh. Genesis 2 zooms in on the forming of Adam from the dust, the garden of Eden, and the creation of Eve. Christians hold different views on how to read the days, but agree on the core message: God is the Creator, creation is good, and humans bear His image.',
    refs: ['Genesis 1:1', 'Genesis 1:27', 'Genesis 1:31', 'Genesis 2:7'] },
  { id: 'babel', patterns: ['babel'], title: 'The Tower of Babel',
    answer: 'After the flood, humanity, speaking one language, settled in Shinar and decided to build a city and a tower “whose top may reach unto heaven” to make a name for themselves. God confused their language and scattered them across the earth. The story exposes human pride — and sets the stage for God calling Abraham in the very next chapter to bless all nations. At Pentecost, the Spirit enabled the gospel to be heard in many languages — a reversal of Babel.',
    refs: ['Genesis 11:4-9', 'Acts 2:5-8'] },
  { id: 'red_sea', patterns: ['red sea', 'parting of the sea', 'crossing the sea'], title: 'Crossing the Red Sea',
    answer: 'After the Passover, Pharaoh let Israel go — then changed his mind and chased them with chariots. Trapped against the sea, the people panicked; Moses said, “Fear ye not, stand still, and see the salvation of the LORD.” God sent a strong east wind that divided the waters, Israel crossed on dry ground, and the waters returned on the pursuing Egyptians. It became Israel’s defining story of rescue.',
    refs: ['Exodus 14:13-14', 'Exodus 14:21-22', 'Exodus 15:1-2'] },
  { id: 'feeding', patterns: ['feeding (of )?(the )?5,?000', 'five thousand', 'loaves and (the )?fish'], title: 'The feeding of the five thousand',
    answer: 'The only miracle (besides the resurrection) recorded in all four Gospels. A great crowd followed Jesus to a remote place. A boy offered five barley loaves and two small fish; Jesus gave thanks, and the disciples distributed food until about five thousand men (plus women and children) were filled, with twelve baskets of leftovers. In John, Jesus then declares, “I am the bread of life.”',
    refs: ['John 6:8-13', 'John 6:35', 'Mark 6:41-44'] },
  { id: 'water_walk', patterns: ['walk(ed|ing)? on (the )?water'], title: 'Jesus walks on water',
    answer: 'After feeding the five thousand, Jesus sent the disciples across the Sea of Galilee. In the night, in a storm, He came walking on the water. Peter asked to come to Him and walked on the water — until he saw the wind, became afraid, and began to sink. Jesus caught him: “O thou of little faith, wherefore didst thou doubt?” The disciples worshipped Him as the Son of God.',
    refs: ['Matthew 14:25-33'] },
  { id: 'cana', patterns: ['water into wine', 'cana', 'wedding at'], title: 'Water into wine at Cana',
    answer: 'Jesus’ first sign in John’s Gospel took place at a wedding in Cana of Galilee. When the wine ran out — a serious embarrassment for the hosts — Mary told the servants, “Whatsoever he saith unto you, do it.” Jesus had six stone jars filled with water, which became the best wine. John says this “manifested forth his glory; and his disciples believed on him.”',
    refs: ['John 2:1-11'] },
  { id: 'furnace', patterns: ['fiery furnace', 'shadrach', 'meshach', 'abednego'], title: 'The fiery furnace',
    answer: 'Shadrach, Meshach and Abednego refused to bow to King Nebuchadnezzar’s golden image. Threatened with a burning furnace, they answered that God was able to deliver them — “but if not,” they still would not bow. Thrown into the furnace, they were seen walking in the fire with a fourth figure “like the Son of God,” and came out unharmed, without even the smell of smoke.',
    refs: ['Daniel 3:16-18', 'Daniel 3:24-27'] },
  { id: 'last_supper', patterns: ['last supper'], title: 'The Last Supper',
    answer: 'On the night before His crucifixion, Jesus shared the Passover meal with His disciples in an upper room. He washed their feet, foretold His betrayal, and took bread and the cup, saying, “This is my body which is given for you” and “This cup is the new testament in my blood.” He commanded them to do this in remembrance of Him, and gave His farewell teaching (John 13–17).',
    refs: ['Luke 22:14-20', 'John 13:12-15'] },
  { id: 'pentecost', patterns: ['pentecost'], title: 'The day of Pentecost',
    answer: 'Fifty days after Passover, the disciples were gathered in Jerusalem when a sound like a rushing mighty wind filled the house, tongues like fire rested on them, and they were filled with the Holy Spirit and spoke in other languages. Peter preached Christ crucified and risen, and about three thousand people believed and were baptized — the birth of the church.',
    refs: ['Acts 2:1-4', 'Acts 2:36-41'] },
  { id: 'damascus', patterns: ['damascus', 'conversion of (saul|paul)'], title: 'Paul on the road to Damascus',
    answer: 'Saul was travelling to Damascus to arrest Christians when a light from heaven flashed around him. He fell to the ground and heard a voice: “Saul, Saul, why persecutest thou me?” It was the risen Jesus. Blinded for three days, he was healed and baptized through Ananias, and immediately began preaching that Jesus is the Son of God.',
    refs: ['Acts 9:3-6', 'Acts 9:17-20'] },
  { id: 'sermon_mount', patterns: ['sermon on the mount'], title: 'The Sermon on the Mount',
    answer: 'Matthew 5–7 is Jesus’ longest recorded sermon. It begins with the Beatitudes, calls disciples salt and light, deepens the law to the level of the heart (anger, lust, honesty, love for enemies), teaches the Lord’s Prayer, warns against worry and judging others, and ends with the wise man who built his house on the rock.',
    refs: ['Matthew 5:3-10', 'Matthew 6:33', 'Matthew 7:24-27'] },
  { id: 'divorce', patterns: ['divorce', 'divorced', 'remarr'], title: 'What does the Bible say about divorce?',
    answer: 'Scripture treats marriage as a lifelong covenant and speaks honestly about the pain of divorce. Malachi records God saying He hates “putting away,” and Jesus taught that Moses permitted divorce “because of the hardness of your hearts,” while from the beginning it was not so. Jesus named sexual immorality as a ground (Matthew 19:9), and Paul addressed a believer abandoned by an unbelieving spouse (1 Corinthians 7:15). Christians differ on how these apply to remarriage, so it is wise to seek a pastor’s counsel.\nAbove all, God’s grace reaches the divorced and the hurting. Divorce is not an unforgivable sin, and no one should remain in a situation where they or their children are unsafe — abuse is never God’s will, and seeking safety and help is right.',
    refs: ['Malachi 2:16', 'Matthew 19:3-9', '1 Corinthians 7:10-15', 'Psalms 34:18'] },
  { id: 'tattoos', patterns: ['tattoo'], title: 'What does the Bible say about tattoos?',
    answer: 'The only direct verse is Leviticus 19:28, part of Israel’s law: “Ye shall not make any cuttings in your flesh for the dead, nor print any marks upon you.” In context it is linked to pagan mourning rites for the dead. Christians differ on whether it applies today, since many such ceremonial laws were fulfilled in Christ.\nThe New Testament principles are helpful for deciding: your body is a temple of the Holy Spirit, so honor God with it; consider your motives and whether it helps or harms your witness; and remember that “man looketh on the outward appearance, but the LORD looketh on the heart.”',
    refs: ['Leviticus 19:28', '1 Corinthians 6:19-20', '1 Corinthians 10:31', '1 Samuel 16:7'] },
  { id: 'christmas', patterns: ['christmas', 'birth of jesus', 'nativity', 'jesus (was )?born'],
    title: 'The birth of Jesus',
    answer: 'Matthew and Luke record Jesus’ birth. The angel Gabriel announced to Mary that she would conceive by the Holy Spirit. Joseph and Mary travelled to Bethlehem for a Roman census, where Jesus was born and laid in a manger. Angels announced the news to shepherds, and later wise men from the east followed a star to worship Him. His birth fulfilled prophecies such as Isaiah 7:14 and Micah 5:2.',
    refs: ['Luke 1:30-35', 'Luke 2:4-14', 'Matthew 2:1-11', 'Isaiah 7:14', 'Micah 5:2'] },
  { id: 'easter', patterns: ['easter', 'good friday', 'holy week', 'palm sunday'],
    title: 'The meaning of Easter',
    answer: 'Easter celebrates the resurrection of Jesus. Holy Week begins with Palm Sunday, when Jesus rode into Jerusalem on a donkey (fulfilling Zechariah 9:9). On Thursday He shared the Last Supper; on Friday He was crucified; and on the third day — Sunday — the women found the tomb empty and the angel said, “He is not here: for he is risen.” The resurrection is the foundation of Christian hope.',
    refs: ['Matthew 21:5-9', 'Luke 22:19-20', 'John 19:30', 'Matthew 28:5-7', '1 Corinthians 15:20'] },
];
