// Key biblical words, used to explain verses ("Key words" sections) and to
// enrich sermon points. `match` lists word forms found in the KJV text.
export const GLOSSARY = [
  { term: 'LORD', match: ['LORD'], caseSensitive: true, def: 'Printed in capitals in the KJV, “LORD” stands for God’s personal covenant name YHWH (often written Yahweh or Jehovah), revealed to Moses as “I AM.” It emphasizes God’s faithfulness to His promises.' },
  { term: 'grace', match: ['grace', 'gracious'], def: 'God’s undeserved favor — His kindness given freely to people who have not earned it and cannot repay it.' },
  { term: 'mercy', match: ['mercy', 'mercies', 'merciful'], def: 'God’s compassion that withholds the judgment we deserve. In the Old Testament it often translates hesed — loyal, covenant love.' },
  { term: 'faith', match: ['faith', 'believe', 'believeth', 'believed'], def: 'Trust in God and His promises — not mere agreement but relying on Him with your whole weight.' },
  { term: 'righteousness', match: ['righteousness', 'righteous', 'just', 'justified', 'justify'], def: 'Being right with God and living rightly. In Paul’s letters, God credits Christ’s righteousness to those who believe (justification).' },
  { term: 'salvation', match: ['salvation', 'saved', 'save', 'saviour'], def: 'Rescue — from danger, from enemies, and above all from sin and its consequences, through God’s power.' },
  { term: 'sin', match: ['sin', 'sins', 'sinned', 'sinner', 'sinners', 'iniquity', 'iniquities', 'transgression', 'transgressions'], def: 'Missing the mark of God’s will; rebellion against Him in thought, word or deed. “Iniquity” stresses crookedness, “transgression” stepping over a boundary.' },
  { term: 'love', match: ['love', 'loved', 'loveth', 'charity'], def: 'Self-giving commitment to another’s good. The New Testament often uses agape — the love God showed in giving His Son. The KJV sometimes renders it “charity.”' },
  { term: 'peace', match: ['peace'], def: 'The Hebrew shalom means wholeness and well-being, not merely the absence of conflict — peace with God, within, and with others.' },
  { term: 'glory', match: ['glory', 'glorify', 'glorified'], def: 'The weight and radiance of God’s presence and worth; to glorify God is to make His greatness known.' },
  { term: 'holy', match: ['holy', 'holiness', 'sanctify', 'sanctified'], def: 'Set apart — God is utterly pure and unique, and He sets His people apart for Himself.' },
  { term: 'Spirit', match: ['Spirit', 'Ghost'], caseSensitive: true, def: 'The Holy Spirit (KJV “Holy Ghost”) is God Himself, present with and in His people — comforting, teaching, empowering and transforming.' },
  { term: 'kingdom', match: ['kingdom'], def: 'God’s reign — His rule breaking into the world through Jesus now, and to be fully established when He returns.' },
  { term: 'covenant', match: ['covenant', 'testament'], def: 'A binding relationship established by God with promises and obligations, such as His covenants with Noah, Abraham, Israel, David, and the new covenant in Christ.' },
  { term: 'redeem', match: ['redeem', 'redeemed', 'redeemer', 'redemption', 'ransom'], def: 'To buy back or set free by paying a price — like a kinsman-redeemer in Ruth, or Christ giving His life as a ransom.' },
  { term: 'repent', match: ['repent', 'repentance', 'repented'], def: 'A change of mind and direction — turning from sin to God.' },
  { term: 'hope', match: ['hope', 'hoped'], def: 'Confident expectation of God’s future goodness, grounded in His promises, not wishful thinking.' },
  { term: 'fear of the LORD', match: ['fear of the LORD', 'fear God', 'feareth'], def: 'Reverent awe and submission toward God — the beginning of wisdom, not terror of an unpredictable God.' },
  { term: 'wisdom', match: ['wisdom', 'wise', 'understanding'], def: 'Skill for living well in God’s world, beginning with reverence for Him.' },
  { term: 'word', match: ['word', 'words'], def: 'God’s self-revelation — His spoken and written word, and in John’s Gospel, Jesus Himself as the eternal Word made flesh.' },
  { term: 'light', match: ['light'], def: 'A picture of God’s truth, purity and life, in contrast to the darkness of sin and ignorance. Jesus called Himself the light of the world.' },
  { term: 'life', match: ['life', 'everlasting', 'eternal'], def: 'Scripture speaks of eternal life not only as endless time but as a new quality of life — knowing God (John 17:3).' },
  { term: 'truth', match: ['truth', 'true'], def: 'What corresponds to reality as God sees it; Jesus said He is the truth and that God’s word is truth.' },
  { term: 'heart', match: ['heart', 'hearts'], def: 'In the Bible, the center of a person — mind, will and emotions together, not only feelings.' },
  { term: 'soul', match: ['soul', 'souls'], def: 'The whole living person, often emphasizing inner life and desire.' },
  { term: 'blessed', match: ['blessed', 'bless', 'blessing'], def: 'To be blessed is to be favored and made flourishing by God — deep well-being that does not depend on circumstances.' },
  { term: 'praise', match: ['praise', 'praised', 'worship'], def: 'Declaring God’s worth with words, song and life.' },
  { term: 'Christ', match: ['Christ', 'Messiah'], caseSensitive: true, def: '“Christ” is the Greek form of the Hebrew “Messiah” — the Anointed One, the promised King who would save God’s people.' },
  { term: 'Son of man', match: ['Son of man'], caseSensitive: true, def: 'Jesus’ favorite title for Himself, drawn from Daniel 7:13-14, where “one like the Son of man” receives an everlasting kingdom.' },
  { term: 'gospel', match: ['gospel'], def: 'Good news — the announcement that God saves sinners through the life, death and resurrection of Jesus.' },
  { term: 'church', match: ['church'], def: 'The assembly of God’s people — not a building, but the community of those who belong to Christ.' },
  { term: 'cross', match: ['cross', 'crucified'], def: 'The Roman instrument of execution on which Jesus died; in the New Testament it becomes the symbol of God’s saving love and of self-denying discipleship.' },
  { term: 'resurrection', match: ['resurrection', 'risen', 'rose again'], def: 'Being raised bodily from death to new, imperishable life — first Jesus, and at the last day those who belong to Him.' },
  { term: 'forgive', match: ['forgive', 'forgiven', 'forgiveness', 'remission'], def: 'To release a debt or offense. “Remission” in the KJV means the cancellation of sins.' },
  { term: 'trust', match: ['trust', 'trusted'], def: 'To rely on God, leaning your full weight on His character and promises.' },
  { term: 'wait', match: ['wait', 'waited'], def: 'Biblical waiting is active, expectant dependence on God, not passive resignation.' },
  { term: 'shepherd', match: ['shepherd'], def: 'A common biblical picture of leadership and care. God is the Shepherd of Israel, and Jesus is the Good Shepherd who lays down His life for the sheep.' },
  { term: 'abide', match: ['abide', 'abideth', 'dwell', 'dwelleth'], def: 'To remain, live in and stay connected — as a branch abides in the vine.' },
  { term: 'temptation', match: ['tempt', 'tempted', 'temptation'], def: 'An enticement to sin, or a trial that tests faith.' },
  { term: 'Amen', match: ['Amen'], caseSensitive: true, def: 'A Hebrew word meaning “so be it” or “truly” — affirming that what was said is reliable.' },
];
