// Major people of the Bible. `events` pair a short description with the
// passage where it happens, so answers always point back to the text.
export const PEOPLE = [
  { id: 'jesus', name: 'Jesus Christ', aliases: ['jesus', 'christ', 'jesus christ', 'messiah', 'son of god', 'lord jesus'],
    summary: 'Jesus of Nazareth is the central figure of the Bible — the eternal Son of God who became man, was born of the virgin Mary in Bethlehem, taught and healed throughout Galilee and Judea, was crucified under Pontius Pilate around AD 30–33, and rose bodily from the dead on the third day. Christians confess Him as Messiah, Savior and Lord.',
    events: [['Born in Bethlehem', 'Luke 2:4-7'], ['Baptized by John; the Father speaks from heaven', 'Matthew 3:16-17'], ['Tempted in the wilderness', 'Matthew 4:1-11'], ['Preaches the Sermon on the Mount', 'Matthew 5:1-12'], ['Raises Lazarus', 'John 11:43-44'], ['Institutes the Lord’s Supper', 'Luke 22:19-20'], ['Crucified', 'John 19:30'], ['Rises from the dead', 'Luke 24:5-7'], ['Ascends to heaven', 'Acts 1:9-11']],
    lessons: ['God came near to rescue us', 'True greatness is serving', 'Forgiveness and new life are offered to all who believe'],
    keyVerses: ['John 1:14', 'John 3:16', 'John 14:6', 'Philippians 2:6-8'] },
  { id: 'moses', name: 'Moses', aliases: ['moses'],
    summary: 'Moses was the Hebrew boy rescued from the Nile and raised in Pharaoh’s palace, who later fled to Midian. At the burning bush God called him to lead Israel out of Egypt. He confronted Pharaoh through the ten plagues, led the people through the Red Sea, received the Law at Sinai, and guided Israel through forty years in the wilderness. He died on Mount Nebo within sight of the promised land.',
    events: [['Rescued from the Nile', 'Exodus 2:1-10'], ['The burning bush', 'Exodus 3:1-14'], ['The Passover', 'Exodus 12:21-30'], ['Crossing the Red Sea', 'Exodus 14:21-31'], ['Receives the Ten Commandments', 'Exodus 20:1-17'], ['Dies on Mount Nebo', 'Deuteronomy 34:1-7']],
    lessons: ['God uses reluctant, imperfect people', 'Intercession matters — Moses repeatedly prayed for the people', 'Meekness is strength under God’s control (Numbers 12:3)'],
    keyVerses: ['Exodus 3:14', 'Exodus 14:14', 'Deuteronomy 34:10'] },
  { id: 'abraham', name: 'Abraham', aliases: ['abraham', 'abram'],
    summary: 'Abraham (first called Abram) left Ur and Haran at God’s call, trusting a promise of land, descendants and blessing for all nations. He is called the father of the faithful because he believed God and it was counted to him for righteousness. In old age he and Sarah received Isaac, and he showed his faith by being willing to offer Isaac on Mount Moriah, where God provided a ram.',
    events: [['Called to leave his country', 'Genesis 12:1-4'], ['God’s covenant and the stars', 'Genesis 15:5-6'], ['Name changed to Abraham', 'Genesis 17:5'], ['Isaac is born', 'Genesis 21:1-3'], ['The offering of Isaac', 'Genesis 22:1-14']],
    lessons: ['Faith obeys before it sees the whole map', 'God keeps promises, even when they seem impossible', 'God will provide (Jehovah-jireh)'],
    keyVerses: ['Genesis 12:2-3', 'Genesis 15:6', 'Romans 4:20-21', 'Hebrews 11:8'] },
  { id: 'david', name: 'King David', aliases: ['david', 'king david'],
    summary: 'David was the youngest son of Jesse of Bethlehem, a shepherd anointed by Samuel to be king. He defeated Goliath, served King Saul, was hunted by him for years, and then reigned over Israel for about forty years, making Jerusalem the capital. Called “a man after God’s own heart,” he wrote many psalms. He also sinned grievously with Bathsheba, repented deeply, and received God’s covenant promise that his throne would last forever — fulfilled in Jesus, the Son of David.',
    events: [['Anointed by Samuel', '1 Samuel 16:12-13'], ['Defeats Goliath', '1 Samuel 17:45-50'], ['Spares Saul’s life', '1 Samuel 24:4-6'], ['God’s covenant with David', '2 Samuel 7:12-16'], ['Sin with Bathsheba and Nathan’s rebuke', '2 Samuel 12:7-13'], ['Prayer of repentance', 'Psalms 51:1-12']],
    lessons: ['God looks on the heart', 'Courage comes from knowing God, not from size or strength', 'Genuine repentance finds mercy'],
    keyVerses: ['1 Samuel 16:7', '1 Samuel 17:47', 'Psalms 23:1', 'Acts 13:22'] },
  { id: 'paul', name: 'The Apostle Paul', aliases: ['paul', 'saul of tarsus', 'apostle paul', 'paul the apostle'],
    summary: 'Paul (Saul of Tarsus) was a zealous Pharisee who persecuted the early church until the risen Jesus confronted him on the road to Damascus. He became the apostle to the Gentiles, made at least three missionary journeys planting churches across the Roman world, and wrote thirteen New Testament letters. He suffered beatings, shipwreck and imprisonment, and was martyred in Rome around AD 67.',
    events: [['Approves of Stephen’s death', 'Acts 8:1'], ['Converted on the Damascus road', 'Acts 9:3-6'], ['Sent out on mission', 'Acts 13:2-3'], ['Singing in the Philippian jail', 'Acts 16:25-31'], ['Preaches in Athens', 'Acts 17:22-31'], ['Shipwrecked on the way to Rome', 'Acts 27:41-44']],
    lessons: ['No one is beyond the reach of grace', 'God’s strength is made perfect in weakness', 'Contentment is learned in Christ'],
    keyVerses: ['Galatians 2:20', 'Philippians 1:21', '2 Corinthians 12:9', '2 Timothy 4:7'] },
  { id: 'peter', name: 'Simon Peter', aliases: ['peter', 'simon peter', 'cephas'],
    summary: 'Peter was a Galilean fisherman called by Jesus to be a fisher of men. Bold and impulsive, he walked on water, confessed Jesus as the Christ, and then denied Him three times on the night of His arrest. After the resurrection Jesus restored him, and at Pentecost Peter preached the sermon that brought three thousand to faith. He led the early church and wrote two letters.',
    events: [['Called to follow Jesus', 'Luke 5:4-11'], ['Walks on water', 'Matthew 14:28-31'], ['Confesses Jesus as the Christ', 'Matthew 16:15-18'], ['Denies Jesus three times', 'Luke 22:54-62'], ['Restored by the risen Jesus', 'John 21:15-17'], ['Preaches at Pentecost', 'Acts 2:14-41']],
    lessons: ['Failure is not final with Jesus', 'Keep your eyes on Christ, not the waves', 'God uses ordinary people boldly'],
    keyVerses: ['Matthew 16:16', 'John 21:17', '1 Peter 5:7'] },
  { id: 'mary', name: 'Mary, the mother of Jesus', aliases: ['mary', 'virgin mary', 'mother of jesus', 'mary mother of jesus'],
    summary: 'Mary was a young woman of Nazareth, engaged to Joseph, when the angel Gabriel announced she would conceive by the Holy Spirit and bear the Son of God. Her response — “be it unto me according to thy word” — is a model of surrendered faith. Her song of praise, the Magnificat, celebrates God who lifts up the humble. She stood at the cross and was with the disciples praying after the resurrection.',
    events: [['The annunciation', 'Luke 1:26-38'], ['Visits Elizabeth; the Magnificat', 'Luke 1:46-55'], ['Gives birth in Bethlehem', 'Luke 2:6-7'], ['At the wedding in Cana', 'John 2:3-5'], ['At the cross', 'John 19:25-27'], ['Praying with the disciples', 'Acts 1:14']],
    lessons: ['Humble surrender to God’s plan', 'Treasure God’s works and ponder them', '“Whatsoever he saith unto you, do it”'],
    keyVerses: ['Luke 1:38', 'Luke 1:46-47', 'Luke 2:19'] },
  { id: 'joseph_ot', name: 'Joseph (son of Jacob)', aliases: ['joseph son of jacob', 'joseph and his brothers', 'joseph in egypt', 'joseph the dreamer'],
    summary: 'Joseph was Jacob’s favored son, given a coat of many colors and dreams of greatness. His jealous brothers sold him into slavery in Egypt. Though falsely accused and imprisoned, he stayed faithful; God gave him the interpretation of Pharaoh’s dreams and raised him to second-in-command of Egypt, where he saved many lives in a famine — including his own family, whom he forgave.',
    events: [['Sold by his brothers', 'Genesis 37:23-28'], ['Resists Potiphar’s wife', 'Genesis 39:7-12'], ['Interprets Pharaoh’s dreams', 'Genesis 41:25-40'], ['Reveals himself to his brothers', 'Genesis 45:1-8'], ['“Ye thought evil… God meant it unto good”', 'Genesis 50:19-21']],
    lessons: ['God is at work even in betrayal and injustice', 'Integrity in private matters', 'Forgiveness can rescue a whole family'],
    keyVerses: ['Genesis 39:2', 'Genesis 50:20'] },
  { id: 'noah', name: 'Noah', aliases: ['noah', 'noah ark', 'noahs ark'],
    summary: 'In a world filled with violence, “Noah found grace in the eyes of the LORD.” God told him to build an ark; Noah obeyed and was saved with his family and the animals through the flood. Afterwards God made a covenant never again to destroy the earth by flood, with the rainbow as its sign.',
    events: [['Finds grace with God', 'Genesis 6:8-9'], ['Builds the ark', 'Genesis 6:14-22'], ['The flood', 'Genesis 7:17-23'], ['God’s covenant and the rainbow', 'Genesis 9:12-16']],
    lessons: ['Faith obeys even when others mock', 'God judges sin yet provides a way of rescue', 'God keeps His covenant'],
    keyVerses: ['Genesis 6:8', 'Genesis 9:13', 'Hebrews 11:7'] },
  { id: 'adam', name: 'Adam and Eve', aliases: ['adam', 'eve', 'adam and eve'],
    summary: 'Adam and Eve were the first man and woman, created in God’s image and placed in the garden of Eden. Tempted by the serpent, they ate from the forbidden tree and sin entered the world, bringing shame, broken relationships and death. Yet God clothed them and promised that the woman’s offspring would crush the serpent’s head.',
    events: [['Created in God’s image', 'Genesis 1:27'], ['Eve formed and given to Adam', 'Genesis 2:21-24'], ['The fall', 'Genesis 3:1-7'], ['The first gospel promise', 'Genesis 3:15']],
    lessons: ['Every person bears God’s image', 'Sin is believing God is holding out on us', 'God pursues sinners ("Where art thou?")'],
    keyVerses: ['Genesis 1:27', 'Genesis 3:9', 'Romans 5:12', '1 Corinthians 15:22'] },
  { id: 'elijah', name: 'Elijah', aliases: ['elijah', 'elias'],
    summary: 'Elijah the Tishbite was a fearless prophet during the reign of wicked King Ahab and Queen Jezebel. He announced a drought, was fed by ravens, raised a widow’s son, and defeated the prophets of Baal on Mount Carmel when God answered by fire. Afterwards, exhausted and afraid, he fled to Horeb, where God met him in a still small voice. He was taken to heaven in a whirlwind.',
    events: [['Fed by ravens', '1 Kings 17:2-6'], ['The widow of Zarephath', '1 Kings 17:8-16'], ['Fire on Mount Carmel', '1 Kings 18:36-39'], ['The still small voice', '1 Kings 19:9-12'], ['Taken up in a whirlwind', '2 Kings 2:11']],
    lessons: ['God provides in drought', 'Even great servants get discouraged — God meets them with rest and His word', 'Choose whom you will follow'],
    keyVerses: ['1 Kings 18:21', '1 Kings 19:12', 'James 5:17'] },
  { id: 'daniel', name: 'Daniel', aliases: ['daniel', 'daniel in the lions den'],
    summary: 'Daniel was taken from Jerusalem to Babylon as a young man. He purposed in his heart not to defile himself, served faithfully under several kings, interpreted dreams, and kept praying three times a day even when it was outlawed — and God shut the lions’ mouths. His visions reveal that God rules over the kingdoms of the world.',
    events: [['Refuses the king’s food', 'Daniel 1:8-16'], ['Interprets Nebuchadnezzar’s dream', 'Daniel 2:27-45'], ['The writing on the wall', 'Daniel 5:25-28'], ['In the lions’ den', 'Daniel 6:10-23'], ['Vision of the Son of man', 'Daniel 7:13-14']],
    lessons: ['Decide beforehand to be faithful', 'Prayer is a lifelong habit, not an emergency measure', 'God is sovereign over nations'],
    keyVerses: ['Daniel 1:8', 'Daniel 6:10', 'Daniel 6:22'] },
  { id: 'esther', name: 'Esther', aliases: ['esther', 'queen esther', 'hadassah'],
    summary: 'Esther (Hadassah) was a Jewish orphan raised by her cousin Mordecai who became queen of Persia. When Haman plotted to destroy the Jews, Esther fasted and then approached the king uninvited at the risk of her life, saying “if I perish, I perish.” Her courage saved her people.',
    events: [['Chosen as queen', 'Esther 2:17'], ['“For such a time as this”', 'Esther 4:13-16'], ['Approaches the king', 'Esther 5:1-3'], ['Exposes Haman', 'Esther 7:3-6']],
    lessons: ['God places us where we are for a purpose', 'Courage often follows prayer and fasting', 'God works even when He seems hidden'],
    keyVerses: ['Esther 4:14', 'Esther 4:16'] },
  { id: 'ruth', name: 'Ruth', aliases: ['ruth'],
    summary: 'Ruth was a Moabite widow who chose loyalty to her mother-in-law Naomi and faith in Israel’s God. Gleaning in the fields of Boaz, she found favor; Boaz redeemed the family land and married her. She became the great-grandmother of King David and is named in the genealogy of Jesus.',
    events: [['“Whither thou goest, I will go”', 'Ruth 1:16-17'], ['Gleaning in Boaz’s field', 'Ruth 2:8-12'], ['Boaz redeems and marries Ruth', 'Ruth 4:9-13']],
    lessons: ['Loyal love (hesed) is beautiful to God', 'God welcomes outsiders', 'God’s providence works through ordinary days'],
    keyVerses: ['Ruth 1:16', 'Ruth 2:12'] },
  { id: 'job', name: 'Job', aliases: ['job'],
    summary: 'Job was a wealthy and blameless man from the land of Uz who lost his children, possessions and health in a single season. He grieved and argued with God but never cursed Him. When God answered from the whirlwind, Job was humbled and comforted, and God restored his fortunes double.',
    events: [['“The LORD gave, and the LORD hath taken away”', 'Job 1:20-22'], ['“I know that my redeemer liveth”', 'Job 19:25'], ['God answers from the whirlwind', 'Job 38:1-4'], ['Job restored', 'Job 42:10-12']],
    lessons: ['Suffering is not always punishment', 'Bring your honest questions to God', 'Seeing God is the answer beneath all answers'],
    keyVerses: ['Job 1:21', 'Job 13:15', 'Job 19:25'] },
  { id: 'john_baptist', name: 'John the Baptist', aliases: ['john the baptist', 'john baptist', 'baptist'],
    summary: 'John the Baptist was the son of the priest Zacharias and Elizabeth, born by God’s miraculous intervention. Living in the wilderness, he preached repentance and baptized in the Jordan, preparing the way for the Messiah. He baptized Jesus and pointed to Him as “the Lamb of God.” He was imprisoned and beheaded by Herod Antipas.',
    events: [['Birth foretold', 'Luke 1:13-17'], ['Preaching in the wilderness', 'Matthew 3:1-6'], ['“Behold the Lamb of God”', 'John 1:29'], ['Baptizes Jesus', 'Matthew 3:13-17'], ['“He must increase, but I must decrease”', 'John 3:30']],
    lessons: ['Point people to Jesus, not to yourself', 'Repentance prepares the heart', 'Faithfulness may be costly'],
    keyVerses: ['John 1:29', 'John 3:30'] },
  { id: 'john_apostle', name: 'John the Apostle', aliases: ['john the apostle', 'apostle john', 'beloved disciple', 'john son of zebedee'],
    summary: 'John, son of Zebedee and brother of James, was a fisherman called by Jesus, one of the inner circle with Peter and James. Called “the disciple whom Jesus loved,” he stood at the cross, where Jesus entrusted His mother to him. Tradition holds that he wrote the Gospel of John, three letters and Revelation, and lived to old age in Ephesus.',
    events: [['Called from his nets', 'Mark 1:19-20'], ['At the transfiguration', 'Matthew 17:1-2'], ['At the cross', 'John 19:26-27'], ['Runs to the empty tomb', 'John 20:2-8'], ['Exiled on Patmos', 'Revelation 1:9']],
    lessons: ['Love is the mark of a disciple', 'Jesus transforms tempers — the “son of thunder” became the apostle of love'],
    keyVerses: ['John 20:31', '1 John 4:8', '1 John 4:19'] },
  { id: 'solomon', name: 'Solomon', aliases: ['solomon', 'king solomon'],
    summary: 'Solomon, son of David and Bathsheba, became Israel’s third king. When God offered him anything, he asked for an understanding heart, and God gave him unmatched wisdom, wealth and peace. He built the first temple in Jerusalem and wrote proverbs and songs. Yet his many foreign wives turned his heart to idols, and the kingdom split after his death.',
    events: [['Asks for wisdom', '1 Kings 3:5-12'], ['The wise judgment', '1 Kings 3:16-28'], ['Dedicates the temple', '1 Kings 8:22-30'], ['His heart turns away', '1 Kings 11:4']],
    lessons: ['Ask God for wisdom', 'A good start does not guarantee a good finish', 'Guard your heart'],
    keyVerses: ['1 Kings 3:9', 'Proverbs 3:5-6'] },
  { id: 'joshua', name: 'Joshua', aliases: ['joshua'],
    summary: 'Joshua, son of Nun, was Moses’ assistant and one of only two spies who trusted God about Canaan. After Moses died, he led Israel across the Jordan, conquered Jericho, and divided the land among the tribes. He finished his life calling Israel to serve the LORD wholeheartedly.',
    events: [['Faithful spy', 'Numbers 14:6-9'], ['Commissioned: be strong and courageous', 'Joshua 1:6-9'], ['Crossing the Jordan', 'Joshua 3:14-17'], ['The fall of Jericho', 'Joshua 6:15-20'], ['“As for me and my house”', 'Joshua 24:15']],
    lessons: ['Courage flows from God’s presence', 'Meditating on God’s Word brings success', 'Choose whom you will serve'],
    keyVerses: ['Joshua 1:9', 'Joshua 24:15'] },
  { id: 'gideon', name: 'Gideon', aliases: ['gideon'],
    summary: 'Gideon was hiding from the Midianites when the angel of the LORD called him a “mighty man of valour.” Hesitant, he asked for signs with a fleece. God reduced his army to 300 men so Israel could not boast, and gave them victory with trumpets, jars and torches.',
    events: [['The angel’s call', 'Judges 6:11-16'], ['The fleece', 'Judges 6:36-40'], ['300 men', 'Judges 7:7'], ['Victory over Midian', 'Judges 7:19-22']],
    lessons: ['God sees who you can become', 'God’s strength shows in our weakness'],
    keyVerses: ['Judges 6:12', 'Judges 7:2'] },
  { id: 'samson', name: 'Samson', aliases: ['samson'],
    summary: 'Samson was a Nazirite from birth, given extraordinary strength by the Spirit of the LORD to fight the Philistines. Yet he was ruled by his appetites, revealed the secret of his strength to Delilah, was captured and blinded. In his final prayer God strengthened him once more.',
    events: [['Birth announced', 'Judges 13:3-5'], ['Kills a lion', 'Judges 14:5-6'], ['Betrayed by Delilah', 'Judges 16:15-21'], ['His final prayer', 'Judges 16:28-30']],
    lessons: ['Gifts without character lead to ruin', 'God still hears the prayer of a broken person'],
    keyVerses: ['Judges 16:28'] },
  { id: 'samuel', name: 'Samuel', aliases: ['samuel'],
    summary: 'Samuel was born in answer to Hannah’s prayer and dedicated to serve God at Shiloh. As a boy he heard God call him by name. He became Israel’s last judge, a prophet and priest, and anointed both Saul and David as king.',
    events: [['Hannah’s prayer', '1 Samuel 1:10-20'], ['“Speak; for thy servant heareth”', '1 Samuel 3:8-10'], ['Anoints Saul', '1 Samuel 10:1'], ['Anoints David', '1 Samuel 16:13']],
    lessons: ['Listen for God’s voice', 'Obedience is better than sacrifice'],
    keyVerses: ['1 Samuel 3:10', '1 Samuel 15:22'] },
  { id: 'jonah', name: 'Jonah', aliases: ['jonah', 'jonas'],
    summary: 'Jonah was a prophet commanded to preach to Nineveh, Israel’s feared enemy. He ran the opposite way, was thrown overboard and swallowed by a great fish, prayed from its belly, and was spat out on land. When he finally preached, Nineveh repented — and Jonah was angry that God showed them mercy.',
    events: [['Runs from God', 'Jonah 1:1-3'], ['Swallowed by a great fish', 'Jonah 1:17'], ['Prayer from the fish', 'Jonah 2:1-9'], ['Nineveh repents', 'Jonah 3:5-10'], ['God’s question to Jonah', 'Jonah 4:10-11']],
    lessons: ['You cannot outrun God', 'God’s mercy is bigger than our prejudices', 'Salvation is of the LORD'],
    keyVerses: ['Jonah 2:9', 'Jonah 4:2'] },
  { id: 'isaiah', name: 'Isaiah', aliases: ['isaiah', 'esaias'],
    summary: 'Isaiah prophesied in Jerusalem for about forty years under kings Uzziah, Jotham, Ahaz and Hezekiah. In the temple he saw the LORD high and lifted up and answered, “Here am I; send me.” His prophecies of Immanuel and the Suffering Servant are among the clearest Old Testament pictures of Jesus.',
    events: [['Vision of the LORD’s holiness', 'Isaiah 6:1-8'], ['The sign of Immanuel', 'Isaiah 7:14'], ['Comfort ye my people', 'Isaiah 40:1-2'], ['The Suffering Servant', 'Isaiah 53:3-6']],
    lessons: ['A vision of God’s holiness leads to confession and mission', 'God comforts His people'],
    keyVerses: ['Isaiah 6:8', 'Isaiah 9:6', 'Isaiah 53:5'] },
  { id: 'jacob', name: 'Jacob (Israel)', aliases: ['jacob', 'israel the man'],
    summary: 'Jacob, son of Isaac and twin of Esau, took his brother’s birthright and blessing by cunning and fled. God met him at Bethel in a dream of a ladder to heaven. After years with Laban, he wrestled with God at Peniel and was renamed Israel. His twelve sons became the twelve tribes.',
    events: [['Buys Esau’s birthright', 'Genesis 25:29-34'], ['The ladder at Bethel', 'Genesis 28:10-17'], ['Wrestles with God', 'Genesis 32:24-30'], ['Reconciled with Esau', 'Genesis 33:4']],
    lessons: ['God’s grace pursues flawed people', 'Transformation can come through struggle'],
    keyVerses: ['Genesis 28:15', 'Genesis 32:28'] },
  { id: 'nehemiah', name: 'Nehemiah', aliases: ['nehemiah'],
    summary: 'Nehemiah was cupbearer to the Persian king Artaxerxes. Grieved by Jerusalem’s broken walls, he prayed, received the king’s permission, and led the rebuilding in just 52 days despite opposition, then worked with Ezra to renew the people’s covenant.',
    events: [['Prays over Jerusalem', 'Nehemiah 1:4-11'], ['A quick prayer before the king', 'Nehemiah 2:4-5'], ['Builds with sword and trowel', 'Nehemiah 4:17-18'], ['The wall is finished', 'Nehemiah 6:15-16']],
    lessons: ['Pray first, then plan and act', 'Leadership perseveres through opposition'],
    keyVerses: ['Nehemiah 4:14', 'Nehemiah 8:10'] },
  { id: 'mary_magdalene', name: 'Mary Magdalene', aliases: ['mary magdalene', 'magdalene'],
    summary: 'Mary of Magdala was delivered by Jesus from seven demons and became one of the women who supported His ministry. She stood near the cross, watched His burial, and was the first person to see the risen Lord, who sent her to tell the disciples.',
    events: [['Delivered and following Jesus', 'Luke 8:1-3'], ['At the cross', 'John 19:25'], ['Meets the risen Jesus', 'John 20:11-18']],
    lessons: ['Those forgiven much love much', 'Jesus calls us by name'],
    keyVerses: ['John 20:16', 'John 20:18'] },
  { id: 'thomas', name: 'Thomas', aliases: ['thomas', 'doubting thomas', 'didymus'],
    summary: 'Thomas, called Didymus (the twin), was one of the twelve apostles. He was absent when the risen Jesus first appeared and said he would not believe without touching the wounds. A week later Jesus appeared and invited him to touch — and Thomas confessed, “My Lord and my God.”',
    events: [['“Let us also go, that we may die with him”', 'John 11:16'], ['“How can we know the way?”', 'John 14:5-6'], ['“My Lord and my God”', 'John 20:24-29']],
    lessons: ['Jesus meets honest doubt with patience', 'Blessed are those who have not seen and yet believe'],
    keyVerses: ['John 20:28-29'] },
  { id: 'judas', name: 'Judas Iscariot', aliases: ['judas', 'judas iscariot'],
    summary: 'Judas Iscariot was one of the twelve apostles and kept the money bag. He agreed with the chief priests to betray Jesus for thirty pieces of silver and identified Him with a kiss in Gethsemane. Afterwards, filled with remorse, he returned the money and took his own life.',
    events: [['Agrees to betray Jesus', 'Matthew 26:14-16'], ['The betrayal kiss', 'Matthew 26:47-50'], ['Remorse', 'Matthew 27:3-5']],
    lessons: ['Proximity to Jesus is not the same as following Him', 'Remorse without turning to God is not repentance'],
    keyVerses: ['Matthew 26:15'] },
  { id: 'stephen', name: 'Stephen', aliases: ['stephen'],
    summary: 'Stephen was one of the seven chosen to serve the Jerusalem church, “a man full of faith and of the Holy Ghost.” He performed wonders and boldly preached Christ to the council. As he was stoned — the first Christian martyr — he saw Jesus standing at God’s right hand and prayed for his killers.',
    events: [['Chosen to serve', 'Acts 6:5'], ['His speech to the council', 'Acts 7:51-53'], ['Sees Jesus and forgives', 'Acts 7:55-60']],
    lessons: ['Serving tables and preaching are both Spirit-filled work', 'Forgive even those who hurt you'],
    keyVerses: ['Acts 7:59-60'] },
  { id: 'nicodemus', name: 'Nicodemus', aliases: ['nicodemus'],
    summary: 'Nicodemus was a Pharisee and member of the Jewish ruling council who came to Jesus by night. Jesus told him he must be born again. Later he defended Jesus before the council and, after the crucifixion, helped Joseph of Arimathea bury Him with costly spices.',
    events: [['Comes to Jesus by night', 'John 3:1-8'], ['Defends Jesus', 'John 7:50-51'], ['Helps bury Jesus', 'John 19:39-40']],
    lessons: ['Even religious people need new birth', 'Faith can grow slowly from questions to courage'],
    keyVerses: ['John 3:3', 'John 3:16'] },
  { id: 'hannah', name: 'Hannah', aliases: ['hannah'],
    summary: 'Hannah was a godly woman grieved by years of childlessness and provocation. She poured out her soul to God at Shiloh and vowed to dedicate a son to Him. God answered with Samuel, and her song of praise celebrates the God who lifts up the lowly.',
    events: [['Pours out her soul', '1 Samuel 1:10-18'], ['Samuel is born', '1 Samuel 1:20'], ['Hannah’s song', '1 Samuel 2:1-2']],
    lessons: ['Bring deep sorrow honestly to God', 'God hears and remembers'],
    keyVerses: ['1 Samuel 1:27', '1 Samuel 2:2'] },
  { id: 'deborah', name: 'Deborah', aliases: ['deborah'],
    summary: 'Deborah was a prophetess and judge of Israel who held court under a palm tree. She summoned Barak to fight the Canaanite general Sisera and went with him into battle. God gave victory, and Deborah and Barak sang a song of triumph.',
    events: [['Judging Israel', 'Judges 4:4-5'], ['Calls Barak to battle', 'Judges 4:6-9'], ['The song of Deborah', 'Judges 5:1-3']],
    lessons: ['God raises up leaders in unlikely places', 'Courage is contagious'],
    keyVerses: ['Judges 4:14'] },
  { id: 'lazarus', name: 'Lazarus', aliases: ['lazarus'],
    summary: 'Lazarus of Bethany was the brother of Martha and Mary and a close friend of Jesus. When he died, Jesus wept and then called him out of the tomb after four days — one of the greatest signs in John’s Gospel, revealing Jesus as “the resurrection, and the life.”',
    events: [['Lazarus falls sick and dies', 'John 11:1-14'], ['“I am the resurrection, and the life”', 'John 11:25-26'], ['“Jesus wept”', 'John 11:35'], ['Raised from the dead', 'John 11:43-44']],
    lessons: ['Jesus grieves with us', 'Jesus has power over death'],
    keyVerses: ['John 11:25-26'] },
  { id: 'zacchaeus', name: 'Zacchaeus', aliases: ['zacchaeus', 'zaccheus'],
    summary: 'Zacchaeus was a rich chief tax collector in Jericho, despised as a collaborator and cheat. Too short to see over the crowd, he climbed a sycamore tree to see Jesus. Jesus called him by name and went to his house, and Zacchaeus responded by giving half his goods to the poor and repaying fourfold anyone he had cheated.',
    events: [['Climbs the sycamore', 'Luke 19:1-4'], ['Jesus invites Himself', 'Luke 19:5-7'], ['Repents and repays', 'Luke 19:8-10']],
    lessons: ['Jesus seeks the lost', 'Real repentance shows in changed actions'],
    keyVerses: ['Luke 19:10'] },
  { id: 'goliath', name: 'Goliath', aliases: ['goliath'],
    summary: 'Goliath was a Philistine champion from Gath, about six cubits and a span tall (roughly 9½ feet in the Hebrew text), who defied the armies of Israel for forty days. The young shepherd David faced him “in the name of the LORD of hosts” and killed him with a sling and a stone.',
    events: [['Goliath’s challenge', '1 Samuel 17:4-10'], ['David’s confidence', '1 Samuel 17:45-47'], ['Goliath falls', '1 Samuel 17:49-50']],
    lessons: ['The battle is the LORD’s', 'Past faithfulness builds present courage'],
    keyVerses: ['1 Samuel 17:47'] },
];
