// Topical teaching. Each topic has an overview, three biblical "movements"
// (used as Q&A sections and as sermon points), practical steps and a prayer.
export const TOPICS = [
  { id: 'anxiety', label: 'Anxiety & Worry', keywords: ['anxiety', 'anxious', 'worry', 'worried', 'worrying', 'stress', 'stressed', 'panic', 'overwhelmed', 'nervous', 'overthinking', 'restless'],
    overview: 'The Bible never shames anxious people; it invites them to transfer the weight. The same God who feeds the birds and clothes the lilies knows exactly what you need, and He offers a peace that does not depend on circumstances being fixed first.',
    points: [
      { title: 'God knows and cares about the details', text: 'Jesus points to birds and flowers: your Father knows what you need before you ask. Anxiety assumes we are on our own; Scripture insists we are not.', refs: ['Matthew 6:25-26', 'Matthew 6:32-34', '1 Peter 5:7'] },
      { title: 'Prayer with thanksgiving is the exchange', text: 'Paul does not say “stop feeling anxious” but “in every thing by prayer… let your requests be made known.” Bringing specific worries to God, alongside specific gratitude, is how the peace that passes understanding guards the heart.', refs: ['Philippians 4:6-7', 'Psalms 55:22'] },
      { title: 'Re-train the mind', text: 'Peace is tied to where the mind rests. Isaiah promises perfect peace to the mind stayed on God, and Paul lists what to think on — things true, honest, just, pure, lovely and of good report.', refs: ['Isaiah 26:3', 'Philippians 4:8', '2 Corinthians 10:5'] },
    ],
    practice: ['Write down each worry and turn it into a one-line prayer.', 'Name three specific things you are thankful for before you pray about the problem.', 'Focus on today’s portion — “sufficient unto the day is the evil thereof.”', 'Take care of your body: rest, eat and talk to someone you trust; if anxiety is persistent, seeing a doctor or counselor is wise, not faithless.'],
    prayer: 'Father, You know every detail I am carrying. I hand You these worries one by one. Guard my heart and mind with Your peace, and help me trust You with tomorrow. In Jesus’ name, Amen.',
    related: ['peace', 'fear', 'trust'] },
  { id: 'fear', label: 'Fear & Courage', keywords: ['fear', 'afraid', 'scared', 'terrified', 'frightened', 'courage', 'brave', 'timid'],
    overview: '“Fear not” is one of the most repeated commands in Scripture — and it almost always comes with a reason: God’s presence. Biblical courage is not the absence of fear but trusting God’s nearness more than the threat in front of you.',
    points: [
      { title: 'Courage rests on God’s presence', text: 'Joshua was not told he was strong enough; he was told “the LORD thy God is with thee whithersoever thou goest.”', refs: ['Joshua 1:9', 'Isaiah 41:10', 'Deuteronomy 31:6'] },
      { title: 'Fear is not your spiritual inheritance', text: 'God has not given a spirit of fear but of power, love and a sound mind. His perfect love casts out the fear of punishment.', refs: ['2 Timothy 1:7', '1 John 4:18', 'Romans 8:15'] },
      { title: 'Turn fear into trust', text: 'David was honest: “What time I am afraid, I will trust in thee.” Faith is a decision made in the presence of fear.', refs: ['Psalms 56:3-4', 'Psalms 27:1', 'Psalms 91:1-2'] },
    ],
    practice: ['Name the fear specifically, then find one promise that answers it.', 'Memorize Psalm 56:3 for moments of panic.', 'Take one small obedient step instead of waiting to feel brave.'],
    prayer: 'Lord, You are my light and my salvation — whom shall I fear? When I am afraid, I choose to trust You. Fill me with power, love and a sound mind. Amen.',
    related: ['anxiety', 'trust', 'strength'] },
  { id: 'grief', label: 'Grief & Loss', keywords: ['grief', 'grieving', 'loss', 'death', 'died', 'dying', 'mourning', 'funeral', 'bereavement', 'passed away', 'miscarriage', 'widow'],
    overview: 'Scripture treats grief as an honest expression of love, not a lack of faith. Jesus Himself wept at Lazarus’ tomb, even knowing He was about to raise him. Christians grieve — but not as those who have no hope.',
    points: [
      { title: 'God draws near to the brokenhearted', text: 'The LORD is close to those with broken hearts; He binds up their wounds. Your tears are seen and remembered.', refs: ['Psalms 34:18', 'Psalms 147:3', 'Psalms 56:8'] },
      { title: 'Jesus weeps with us', text: 'At Lazarus’ tomb “Jesus wept.” God does not stand at a distance from our sorrow; in Christ He entered it.', refs: ['John 11:33-35', 'Isaiah 53:3-4'] },
      { title: 'Grief with hope', text: 'For believers, death is not the end. Paul comforts grieving Christians with the promise of resurrection, and Revelation pictures God wiping away every tear.', refs: ['1 Thessalonians 4:13-14', 'John 11:25-26', 'Revelation 21:4'] },
    ],
    practice: ['Give yourself permission to grieve; read a lament psalm aloud (Psalm 42 or 88).', 'Let others help with practical needs.', 'Write a letter to God about the one you lost.', 'If grief becomes overwhelming or long-lasting, reach out to a pastor, grief counselor or doctor.'],
    prayer: 'God of all comfort, my heart is heavy. Thank You that You are near to the brokenhearted. Hold me in this sorrow, and anchor me in the hope of resurrection. Amen.',
    related: ['hope', 'heaven', 'comfort'] },
  { id: 'forgiveness', label: 'Forgiveness', keywords: ['forgive', 'forgiveness', 'forgiving', 'resentment', 'bitter', 'bitterness', 'grudge', 'hurt me', 'betrayed', 'offended'],
    overview: 'Forgiveness in the Bible flows in two directions: the forgiveness we receive from God through Christ, and the forgiveness we extend to others because we have been forgiven. Forgiving is not pretending the wrong did not happen or excusing it; it is releasing the debt to God, who judges justly.',
    points: [
      { title: 'We are forgiven completely', text: 'If we confess our sins, God is faithful and just to forgive. He removes our transgressions as far as the east is from the west.', refs: ['1 John 1:9', 'Psalms 103:10-12', 'Ephesians 1:7'] },
      { title: 'Forgiven people forgive', text: 'Paul’s logic is simple: forgive “even as God for Christ’s sake hath forgiven you.” Jesus’ parable of the unforgiving servant shows how absurd it is to receive mercy and withhold it.', refs: ['Ephesians 4:32', 'Colossians 3:13', 'Matthew 18:21-22', 'Matthew 18:32-35'] },
      { title: 'Forgiveness trusts God with justice', text: 'We do not avenge ourselves; we leave room for God. Forgiveness releases the debt; reconciliation and trust may take time and require repentance from the other person.', refs: ['Romans 12:17-19', 'Romans 12:21', 'Genesis 50:19-21'] },
    ],
    practice: ['Name the specific debt you are releasing, and say so to God in prayer.', 'Pray for the person’s good (Matthew 5:44).', 'Set healthy boundaries where trust has been broken — forgiveness is not the same as staying in harm’s way.', 'Expect to forgive again when the memory returns; it is often a process.'],
    prayer: 'Father, thank You for forgiving me so fully. I choose to release this debt to You. Heal my heart, and help me to love as You have loved me. Amen.',
    related: ['grace', 'anger', 'love'] },
  { id: 'love', label: 'Love', keywords: ['love', 'loving', 'loved', 'charity', 'compassion', 'kindness'],
    overview: '“God is love” (1 John 4:8). Biblical love is not mainly a feeling but a self-giving commitment to another’s good, defined supremely at the cross.',
    points: [
      { title: 'Love begins with God', text: 'We love because He first loved us. God demonstrated His love while we were still sinners.', refs: ['1 John 4:9-10', '1 John 4:19', 'Romans 5:8'] },
      { title: 'Love is patient action', text: '1 Corinthians 13 describes love in verbs: it suffers long, is kind, does not envy, is not puffed up, keeps no record of wrongs, and never fails.', refs: ['1 Corinthians 13:4-7', '1 Corinthians 13:13'] },
      { title: 'Love fulfills the law', text: 'Jesus summarized the law as loving God with all our heart and our neighbor as ourselves — and gave a new commandment: love one another as I have loved you.', refs: ['Matthew 22:37-39', 'John 13:34-35', 'Romans 13:10'] },
    ],
    practice: ['Read 1 Corinthians 13:4-7 replacing “charity” with your name — where do you fall short?', 'Do one hidden act of kindness this week.', 'Ask: what would love do here, not what do I feel?'],
    prayer: 'Lord, thank You for loving me first. Pour Your love into my heart by Your Spirit, and make me patient, kind and generous toward others. Amen.',
    related: ['marriage', 'forgiveness', 'kindness'] },
  { id: 'marriage', label: 'Marriage & Relationships', keywords: ['marriage', 'married', 'husband', 'wife', 'spouse', 'wedding', 'divorce', 'dating', 'boyfriend', 'girlfriend', 'relationship', 'engaged'],
    overview: 'Marriage in Scripture is a covenant designed by God from creation — a man and a woman becoming one flesh — and ultimately a picture of Christ’s love for His church. Healthy relationships are built on mutual honor, sacrificial love and shared faith.',
    points: [
      { title: 'God designed marriage', text: 'From the beginning, God said it was not good for man to be alone, and joined husband and wife as one flesh. Jesus reaffirmed this design.', refs: ['Genesis 2:18', 'Genesis 2:24', 'Matthew 19:4-6'] },
      { title: 'Love like Christ', text: 'Paul calls husbands to love their wives as Christ loved the church and gave Himself for it, and calls both to submit to one another in the fear of God.', refs: ['Ephesians 5:21', 'Ephesians 5:25', 'Colossians 3:18-19'] },
      { title: 'Build on wisdom', text: 'A threefold cord is not quickly broken. Choose partners who share your faith, speak gently, and keep short accounts of anger.', refs: ['Ecclesiastes 4:9-12', '2 Corinthians 6:14', 'Ephesians 4:26'] },
    ],
    practice: ['Pray together for five minutes each day.', 'Practice quick apologies and full forgiveness.', 'Schedule regular, unhurried time to talk.', 'Seek a trusted pastor or counselor early when conflict repeats.'],
    prayer: 'Lord, You are the author of marriage. Make our home a place of patient love, honest words and quick forgiveness, and let our love reflect Yours. Amen.',
    related: ['love', 'family', 'forgiveness'] },
  { id: 'family', label: 'Parenting & Family', keywords: ['parenting', 'parent', 'parents', 'children', 'child', 'kids', 'family', 'son', 'daughter', 'teenager', 'mother', 'father', 'raise'],
    overview: 'Scripture pictures the home as the first place faith is passed on — not through occasional lessons but through everyday life, modeled love and patient instruction.',
    points: [
      { title: 'Faith woven into daily life', text: 'Moses told parents to talk about God’s words when sitting at home, walking, lying down and rising up.', refs: ['Deuteronomy 6:5-7', 'Proverbs 22:6'] },
      { title: 'Firm and tender', text: 'Fathers are told not to provoke children to wrath but to bring them up in the nurture and admonition of the Lord. Discipline is an expression of love.', refs: ['Ephesians 6:4', 'Colossians 3:21', 'Hebrews 12:11'] },
      { title: 'Children are a gift', text: 'Children are a heritage from the LORD, and Jesus welcomed little ones into His arms.', refs: ['Psalms 127:3', 'Mark 10:14-16'] },
    ],
    practice: ['Read a short Bible story at bedtime and ask one question about it.', 'Pray aloud for your children by name.', 'Apologize to your kids when you get it wrong — it teaches grace.'],
    prayer: 'Father, give me wisdom and patience as a parent. Help my children to know You and love You, and let our home reflect Your grace. Amen.',
    related: ['marriage', 'love', 'wisdom'] },
  { id: 'faith', label: 'Faith & Doubt', keywords: ['faith', 'believe', 'belief', 'doubt', 'doubting', 'unbelief', 'trust god', 'skeptic'],
    overview: 'Hebrews defines faith as “the substance of things hoped for, the evidence of things not seen.” Faith is not a leap in the dark but trust in a God who has proven Himself faithful. Doubt is not the opposite of faith; unbelief that refuses to bring questions to God is.',
    points: [
      { title: 'What faith is', text: 'Faith is confident trust in God’s character and promises, even before we see the outcome. Without faith it is impossible to please Him.', refs: ['Hebrews 11:1', 'Hebrews 11:6', '2 Corinthians 5:7'] },
      { title: 'How faith grows', text: 'Faith comes by hearing, and hearing by the word of God. It grows like a mustard seed — small beginnings, real growth.', refs: ['Romans 10:17', 'Matthew 17:20', 'Mark 4:30-32'] },
      { title: 'Honest doubt is welcome', text: 'A desperate father prayed, “Lord, I believe; help thou mine unbelief,” and Jesus helped him. Jesus met Thomas’ doubts with His wounds.', refs: ['Mark 9:23-24', 'John 20:27-29'] },
    ],
    practice: ['Bring your honest questions to God in prayer.', 'Read one Gospel straight through and watch who Jesus is.', 'Keep a record of answered prayers to remember God’s faithfulness.'],
    prayer: 'Lord, I believe; help my unbelief. Strengthen my faith through Your Word and show me Your faithfulness again today. Amen.',
    related: ['trust', 'salvation', 'prayer'] },
  { id: 'trust', label: 'Trusting God', keywords: ['trust', 'trusting', 'surrender', 'control', 'uncertain', 'uncertainty', 'waiting', 'wait on god'],
    overview: 'Trust means leaning your whole weight on God rather than your own understanding — especially when you cannot see how things will work out.',
    points: [
      { title: 'Lean on God, not your understanding', text: 'Proverbs calls us to trust the LORD with all our heart and acknowledge Him in all our ways; He will direct our paths.', refs: ['Proverbs 3:5-6', 'Psalms 37:5'] },
      { title: 'God works all things for good', text: 'For those who love God, all things work together for good — not that all things are good, but that God weaves even painful things into His purpose.', refs: ['Romans 8:28', 'Genesis 50:20', 'Jeremiah 29:11'] },
      { title: 'Waiting is active trust', text: 'Those who wait upon the LORD renew their strength. Waiting is not passivity but expectant dependence.', refs: ['Isaiah 40:31', 'Psalms 27:14', 'Lamentations 3:25-26'] },
    ],
    practice: ['Identify one area you are trying to control and pray it into God’s hands daily.', 'Remember past faithfulness — write down three times God came through.'],
    prayer: 'Lord, I trust You with all my heart. I don’t understand everything, but I acknowledge You. Direct my path. Amen.',
    related: ['faith', 'anxiety', 'purpose'] },
  { id: 'peace', label: 'Peace', keywords: ['peace', 'calm', 'rest', 'quiet', 'tranquil', 'stillness'],
    overview: 'Biblical peace (shalom) means wholeness — peace with God, peace within, and peace with others. Jesus offers a peace “not as the world giveth.”',
    points: [
      { title: 'Peace with God', text: 'Being justified by faith, we have peace with God through our Lord Jesus Christ. This is the foundation of every other peace.', refs: ['Romans 5:1', 'Colossians 1:20'] },
      { title: 'The peace of God', text: 'Jesus leaves His peace with His disciples, and Paul promises a peace that passes all understanding guarding hearts and minds.', refs: ['John 14:27', 'John 16:33', 'Philippians 4:7'] },
      { title: 'Rest for the weary', text: 'Jesus invites all who labour and are heavy laden to come to Him for rest. Be still, and know that He is God.', refs: ['Matthew 11:28-30', 'Psalms 46:10', 'Isaiah 26:3'] },
    ],
    practice: ['Begin the day with five quiet minutes reading a psalm.', 'Make peace with someone you are at odds with (Romans 12:18).', 'Practice a weekly sabbath rhythm of rest.'],
    prayer: 'Prince of Peace, quiet my heart. Thank You that I have peace with God through Jesus. Let Your peace rule in my heart today. Amen.',
    related: ['anxiety', 'rest', 'trust'] },
  { id: 'hope', label: 'Hope', keywords: ['hope', 'hopeless', 'despair', 'discouraged', 'discouragement', 'give up', 'giving up'],
    overview: 'Biblical hope is not wishful thinking but confident expectation grounded in God’s character and the resurrection of Jesus. It is “an anchor of the soul, both sure and stedfast.”',
    points: [
      { title: 'Hope that is alive', text: 'God has begotten us again unto a lively hope by the resurrection of Jesus Christ from the dead.', refs: ['1 Peter 1:3', 'Hebrews 6:19'] },
      { title: 'Mercies new every morning', text: 'Written amid Jerusalem’s ruins, Lamentations declares that God’s compassions fail not; they are new every morning.', refs: ['Lamentations 3:21-23', 'Psalms 42:11'] },
      { title: 'The God of hope', text: 'Paul prays that the God of hope would fill us with all joy and peace in believing, that we may abound in hope.', refs: ['Romans 15:13', 'Romans 5:3-5', 'Romans 8:24-25'] },
    ],
    practice: ['Talk back to your soul like Psalm 42: “Why art thou cast down?”', 'Read the end of the story — Revelation 21–22.', 'If hopelessness is heavy or persistent, please talk to someone you trust or a professional today.'],
    prayer: 'God of hope, fill me with joy and peace as I trust You. Your mercies are new this morning. Anchor my soul in You. Amen.',
    related: ['grief', 'depression', 'faith'] },
  { id: 'depression', label: 'Depression & Sadness', keywords: ['depressed', 'depression', 'sad', 'sadness', 'lonely', 'loneliness', 'alone', 'empty', 'numb', 'worthless', 'down'],
    overview: 'Many heroes of faith experienced deep darkness — David, Elijah, Jeremiah, even Jesus in Gethsemane. Scripture gives language for lament and shows God meeting weary people gently, often first with rest and food, then with His presence.',
    points: [
      { title: 'You are not the first', text: 'Elijah asked to die under a juniper tree. God did not lecture him; He let him sleep, fed him, and then spoke in a still small voice.', refs: ['1 Kings 19:4-8', '1 Kings 19:11-12'] },
      { title: 'Lament is a form of faith', text: 'The psalmists pour out complaint honestly — “How long, O LORD?” — and still address God as “my God.”', refs: ['Psalms 13:1-6', 'Psalms 42:5', 'Psalms 88:1-3'] },
      { title: 'You are never alone', text: 'God promises never to leave or forsake His people; nothing can separate us from His love.', refs: ['Hebrews 13:5', 'Romans 8:38-39', 'Psalms 139:7-10'] },
    ],
    practice: ['Tell someone you trust how you are really doing.', 'Attend to basics: sleep, food, movement and sunlight.', 'Pray a lament psalm as your own words.', 'Depression is a real health condition — seeing a doctor or counselor is wise and good. If you ever feel unsafe, contact local emergency services or a crisis line right away.'],
    prayer: 'Lord, I feel low and weary. Thank You that You are near to the brokenhearted. Meet me in the dark, give me rest, and lead me to the help I need. Amen.',
    related: ['hope', 'loneliness', 'grief'] },
  { id: 'strength', label: 'Strength & Weariness', keywords: ['strength', 'strong', 'weak', 'weakness', 'tired', 'exhausted', 'weary', 'burnout', 'burned out', 'struggle', 'struggling'],
    overview: 'God’s power is most clearly displayed not where we are strong but where we are weak. His promise is not to remove every burden but to give strength sufficient for it.',
    points: [
      { title: 'Strength renewed', text: 'The everlasting God does not faint or grow weary; He gives power to the faint and renews the strength of those who wait on Him.', refs: ['Isaiah 40:28-31'] },
      { title: 'Strength in weakness', text: 'God told Paul, “My grace is sufficient for thee: for my strength is made perfect in weakness.”', refs: ['2 Corinthians 12:9-10', '2 Corinthians 4:7-9'] },
      { title: 'Christ is the source', text: 'Paul’s “I can do all things” is about contentment in every circumstance through Christ who strengthens him.', refs: ['Philippians 4:11-13', 'Psalms 73:26', 'Nehemiah 8:10'] },
    ],
    practice: ['Take an honest inventory of your load and say no to one non-essential.', 'Rest is obedience, not laziness — schedule it.', 'Ask God for strength for today, not for the whole month.'],
    prayer: 'Lord, I am weary. Renew my strength as I wait on You. Let Your grace be sufficient for me today. Amen.',
    related: ['rest', 'trust', 'perseverance'] },
  { id: 'rest', label: 'Rest & Sabbath', keywords: ['sabbath', 'rest', 'busy', 'overworked', 'sleep', 'insomnia'],
    overview: 'God built rest into creation itself — He rested on the seventh day and gave the sabbath as a gift. Rest is an act of trust that the world does not depend on our constant effort.',
    points: [
      { title: 'Rest is part of God’s design', text: 'God rested on the seventh day and blessed it; the sabbath was made for man.', refs: ['Genesis 2:2-3', 'Exodus 20:8-10', 'Mark 2:27'] },
      { title: 'Jesus gives soul rest', text: 'Come unto me… and I will give you rest. His yoke is easy and His burden light.', refs: ['Matthew 11:28-30'] },
      { title: 'Sleep as trust', text: 'God gives His beloved sleep; it is vain to rise early and sit up late eating the bread of sorrows.', refs: ['Psalms 127:2', 'Psalms 4:8', 'Psalms 3:5'] },
    ],
    practice: ['Choose one weekly block for unhurried rest and worship.', 'Put devices away before sleep and read a psalm instead.'],
    prayer: 'Lord, teach me to rest in You. I lay down my work and my worries, trusting You to keep me. Amen.',
    related: ['peace', 'strength'] },
  { id: 'purpose', label: 'Purpose & God’s Will', keywords: ['purpose', 'calling', 'called', 'gods will', "god's will", 'will of god', 'direction', 'future', 'destiny', 'meaning', 'decision', 'decide', 'career', 'path'],
    overview: 'Much of God’s will is already revealed — love God, love people, grow in holiness, give thanks. Within that, God guides the next step through His Word, wise counsel, prayer and circumstances.',
    points: [
      { title: 'You were made on purpose', text: 'We are God’s workmanship, created in Christ Jesus unto good works, which God prepared beforehand. He has plans to give you a future and a hope.', refs: ['Ephesians 2:10', 'Jeremiah 29:11', 'Psalms 139:13-16'] },
      { title: 'God’s revealed will', text: 'Be renewed in mind to prove God’s will; rejoice, pray, give thanks — “this is the will of God in Christ Jesus concerning you.”', refs: ['Romans 12:1-2', '1 Thessalonians 5:16-18', 'Micah 6:8'] },
      { title: 'Guidance for the next step', text: 'Thy word is a lamp unto my feet — enough light for the next step. Commit your works to the LORD and He establishes your plans.', refs: ['Psalms 119:105', 'Proverbs 16:3', 'Proverbs 16:9', 'James 1:5'] },
    ],
    practice: ['Obey what you already know God wants today.', 'Ask two mature believers for counsel (Proverbs 15:22).', 'Pray, then make the wisest decision you can and trust God to redirect you.'],
    prayer: 'Lord, I want my life to count for You. Renew my mind, show me the next step, and give me courage to follow. Amen.',
    related: ['wisdom', 'trust', 'work'] },
  { id: 'wisdom', label: 'Wisdom', keywords: ['wisdom', 'wise', 'guidance', 'advice', 'confused', 'unsure', 'understanding', 'discernment'],
    overview: 'In Scripture wisdom is skill for living in God’s world. It begins with the fear of the LORD and is generously given to anyone who asks.',
    points: [
      { title: 'Wisdom starts with reverence', text: 'The fear of the LORD is the beginning of knowledge and wisdom.', refs: ['Proverbs 1:7', 'Proverbs 9:10', 'Psalms 111:10'] },
      { title: 'Ask for it', text: 'If any of you lack wisdom, let him ask of God, that giveth to all men liberally. Solomon asked for an understanding heart and God was pleased.', refs: ['James 1:5', '1 Kings 3:9-12'] },
      { title: 'Wisdom from above looks like something', text: 'Heavenly wisdom is pure, peaceable, gentle, easy to be intreated, full of mercy and good fruits.', refs: ['James 3:17', 'Proverbs 3:13-17'] },
    ],
    practice: ['Read the Proverbs chapter that matches today’s date.', 'Seek counsel before big decisions.', 'Ask: what would a person who fears God do here?'],
    prayer: 'Father, I lack wisdom. Please give it to me generously, as You promised, and help me walk in it. Amen.',
    related: ['purpose', 'decision'] },
  { id: 'salvation', label: 'Salvation & the Gospel', keywords: ['salvation', 'saved', 'save me', 'be saved', 'gospel', 'born again', 'eternal life', 'accept jesus', 'become a christian', 'how to be saved', 'redemption'],
    overview: 'The gospel is the good news that God saves sinners through Jesus Christ. We cannot earn it; we receive it by grace through faith — turning from sin and trusting Christ, who died for our sins and rose again.',
    points: [
      { title: 'Our need', text: 'All have sinned and come short of the glory of God, and the wages of sin is death.', refs: ['Romans 3:23', 'Romans 6:23', 'Isaiah 59:2'] },
      { title: 'God’s provision', text: 'God so loved the world that He gave His only begotten Son. Christ died for our sins, was buried, and rose again the third day.', refs: ['John 3:16', 'Romans 5:8', '1 Corinthians 15:3-4'] },
      { title: 'Our response', text: 'By grace you are saved through faith — not of works. Confess with your mouth the Lord Jesus and believe in your heart that God raised Him from the dead.', refs: ['Ephesians 2:8-9', 'Romans 10:9-10', 'Acts 3:19', 'John 1:12'] },
    ],
    practice: ['Talk honestly to God: admit your need, trust Christ, and follow Him.', 'Tell a Christian friend or pastor about your decision.', 'Start reading the Gospel of John.', 'Find a Bible-teaching church and ask about baptism.'],
    prayer: 'Lord Jesus, I know I have sinned and cannot save myself. I believe You died for me and rose again. I turn from my sin and trust You as my Savior and Lord. Thank You for forgiving me and giving me new life. Amen.',
    related: ['grace', 'faith', 'baptism'] },
  { id: 'grace', label: 'Grace', keywords: ['grace', 'mercy', 'undeserved', 'unworthy', 'favor'],
    overview: 'Grace is God’s undeserved favor — giving us what we could never earn. Mercy withholds the punishment we deserve; grace gives the blessing we don’t.',
    points: [
      { title: 'Saved by grace', text: 'Salvation is the gift of God, not of works, lest any man should boast.', refs: ['Ephesians 2:4-9', 'Titus 3:5'] },
      { title: 'Grace that is sufficient', text: 'God’s grace is enough for every weakness; we can come boldly to the throne of grace to find help.', refs: ['2 Corinthians 12:9', 'Hebrews 4:16'] },
      { title: 'Grace that trains us', text: 'Grace does not excuse sin; it teaches us to deny ungodliness and live soberly, righteously and godly.', refs: ['Titus 2:11-12', 'Romans 6:1-2', 'Romans 6:14'] },
    ],
    practice: ['Thank God for three specific undeserved gifts today.', 'Show grace to someone who doesn’t “deserve” it.'],
    prayer: 'Gracious Father, thank You for loving me when I did not deserve it. Let Your grace change how I live and how I treat others. Amen.',
    related: ['salvation', 'forgiveness'] },
  { id: 'prayer', label: 'Prayer', keywords: ['prayer', 'praying', 'pray', 'how to pray', 'unanswered prayer', 'intercession'],
    overview: 'Prayer is conversation with God as Father. Jesus taught His disciples a pattern of prayer, prayed often Himself, and promised that the Father hears.',
    points: [
      { title: 'Jesus’ pattern', text: 'The Lord’s Prayer moves from God’s name, kingdom and will to our daily bread, forgiveness and protection.', refs: ['Matthew 6:9-13', 'Luke 11:1-4'] },
      { title: 'Pray with confidence and persistence', text: 'Ask, seek, knock. Jesus told a parable so that people would always pray and not lose heart.', refs: ['Matthew 7:7-11', 'Luke 18:1', 'Hebrews 4:16'] },
      { title: 'When answers are slow', text: 'God hears even when He says “wait” or “no.” The Spirit helps our weakness and intercedes for us; Jesus Himself prayed “not my will, but thine.”', refs: ['Romans 8:26-27', 'Luke 22:42', '1 John 5:14-15'] },
    ],
    practice: ['Use ACTS: Adoration, Confession, Thanksgiving, Supplication.', 'Keep a prayer list and record answers.', 'Pray a psalm back to God word by word.'],
    prayer: 'Our Father in heaven, teach me to pray. Draw me close, align my desires with Yours, and help me trust You with every answer. Amen.',
    related: ['faith', 'fasting', 'worship'] },
  { id: 'temptation', label: 'Temptation & Sin', keywords: ['temptation', 'tempted', 'sin', 'sinning', 'addiction', 'addicted', 'lust', 'pornography', 'porn', 'habit', 'struggle with sin', 'relapse', 'alcohol', 'drinking', 'drunk', 'smoking', 'drugs', 'gambling'],
    overview: 'Temptation is common to everyone — even Jesus was tempted, yet without sin. God promises a way of escape and gives His Spirit to empower real change.',
    points: [
      { title: 'You are not alone', text: 'No temptation is unique; God is faithful and will provide a way of escape. Jesus sympathizes because He was tempted in every way.', refs: ['1 Corinthians 10:13', 'Hebrews 4:15'] },
      { title: 'How temptation works', text: 'Desire conceived gives birth to sin, and sin when finished brings death. Catch it early.', refs: ['James 1:13-15', 'Genesis 4:7'] },
      { title: 'How to fight', text: 'Jesus answered temptation with Scripture. Walk in the Spirit, flee youthful lusts, and confess to one another.', refs: ['Matthew 4:4', 'Galatians 5:16', '2 Timothy 2:22', 'James 5:16'] },
    ],
    practice: ['Identify your triggers and remove easy access.', 'Memorize one verse for your specific battle.', 'Find an accountability partner.', 'For addiction, combine spiritual support with professional help.'],
    prayer: 'Lord, You know my weakness. Lead me not into temptation, deliver me from evil, and strengthen me by Your Spirit to choose the way of escape. Amen.',
    related: ['forgiveness', 'holiness', 'grace'] },
  { id: 'anger', label: 'Anger', keywords: ['anger', 'angry', 'mad', 'frustrated', 'frustration', 'rage', 'temper', 'irritated'],
    overview: 'Anger itself is not always sin — God is angry at injustice — but human anger easily becomes destructive. Scripture calls us to be slow to anger and quick to resolve conflict.',
    points: [
      { title: 'Be angry and sin not', text: 'Don’t let the sun go down on your wrath or give place to the devil.', refs: ['Ephesians 4:26-27', 'Psalms 4:4'] },
      { title: 'Slow to wrath', text: 'Be swift to hear, slow to speak, slow to wrath; the wrath of man does not work God’s righteousness.', refs: ['James 1:19-20', 'Proverbs 14:29'] },
      { title: 'Gentle words win', text: 'A soft answer turns away wrath, but grievous words stir up anger.', refs: ['Proverbs 15:1', 'Proverbs 16:32', 'Colossians 3:8'] },
    ],
    practice: ['Pause and pray before responding.', 'Ask what is underneath the anger — hurt, fear or injustice?', 'Resolve conflicts the same day where possible.'],
    prayer: 'Lord, calm my heart. Make me slow to anger, quick to listen, and gentle in my words. Amen.',
    related: ['forgiveness', 'peace', 'self-control'] },
  { id: 'money', label: 'Money & Provision', keywords: ['money', 'finances', 'financial', 'debt', 'poor', 'poverty', 'provision', 'provide', 'rent', 'bills', 'wealth', 'rich', 'tithe', 'tithing', 'giving', 'generosity'],
    overview: 'Jesus spoke often about money because it competes for our hearts. Scripture calls us to trust God as Provider, work diligently, avoid the love of money, and give generously.',
    points: [
      { title: 'God provides', text: 'Seek first the kingdom of God and these things will be added; my God shall supply all your need.', refs: ['Matthew 6:31-33', 'Philippians 4:19', 'Psalms 37:25'] },
      { title: 'Guard against greed', text: 'The love of money is a root of all kinds of evil; godliness with contentment is great gain.', refs: ['1 Timothy 6:6-10', 'Hebrews 13:5', 'Luke 12:15'] },
      { title: 'Give generously and plan wisely', text: 'God loves a cheerful giver. Honor the LORD with your substance, and be diligent like the ant.', refs: ['2 Corinthians 9:6-8', 'Proverbs 3:9-10', 'Proverbs 6:6-8', 'Malachi 3:10'] },
    ],
    practice: ['Make a simple monthly budget and pray over it.', 'Give first, save second, live on the rest.', 'Thank God for daily bread before asking for more.'],
    prayer: 'Provider God, I trust You with my needs. Free me from fear and greed, make me wise with what I have, and generous to others. Amen.',
    related: ['work', 'contentment', 'trust'] },
  { id: 'work', label: 'Work & Career', keywords: ['work', 'job', 'jobs', 'career', 'workplace', 'boss', 'colleague', 'business', 'unemployed', 'promotion', 'interview'],
    overview: 'Work was given before the fall — Adam was placed in the garden “to dress it and to keep it.” Ordinary work becomes worship when done heartily as unto the Lord.',
    points: [
      { title: 'Work is a gift', text: 'God placed man in Eden to work it; enjoying the good of our labour is a gift of God.', refs: ['Genesis 2:15', 'Ecclesiastes 3:13'] },
      { title: 'Work as unto the Lord', text: 'Whatever you do, do it heartily as to the Lord, not to men.', refs: ['Colossians 3:23-24', '1 Corinthians 10:31'] },
      { title: 'Integrity and diligence', text: 'The hand of the diligent shall bear rule. Commit your works to the LORD.', refs: ['Proverbs 12:24', 'Proverbs 16:3', 'Proverbs 22:29'] },
    ],
    practice: ['Pray for your workplace and colleagues by name.', 'Do excellent work even when unseen.', 'If job-hunting, commit each application to God and keep going.'],
    prayer: 'Lord, I offer my work to You. Help me serve with excellence and integrity, and provide for my needs. Amen.',
    related: ['purpose', 'money'] },
  { id: 'healing', label: 'Healing & Sickness', keywords: ['healing', 'heal', 'healed', 'sick', 'sickness', 'illness', 'disease', 'cancer', 'pain', 'hospital', 'surgery', 'diagnosis'],
    overview: 'Jesus healed many and showed God’s compassion for the sick. Scripture invites us to pray for healing with faith, to receive medical care gratefully, and to trust God’s goodness when healing is delayed.',
    points: [
      { title: 'God heals', text: 'Bless the LORD… who healeth all thy diseases. Jesus went about healing all manner of sickness.', refs: ['Psalms 103:2-3', 'Matthew 4:23', 'Jeremiah 17:14'] },
      { title: 'Pray together', text: 'Is any sick among you? Let him call for the elders of the church and let them pray over him.', refs: ['James 5:14-16'] },
      { title: 'Grace when healing waits', text: 'Paul prayed three times for his thorn to be removed and received sufficient grace instead. Ultimate healing is promised when God makes all things new.', refs: ['2 Corinthians 12:7-9', 'Romans 8:18', 'Revelation 21:4'] },
    ],
    practice: ['Ask your church leaders to pray with you.', 'Follow medical advice — doctors are among God’s good gifts (Luke the physician wrote two books of the Bible).', 'Write the promises you are holding onto and read them daily.'],
    prayer: 'Lord, You are the Healer. I ask You to bring healing to my body and peace to my heart. Give wisdom to those caring for me, and help me trust You in every outcome. Amen.',
    related: ['strength', 'faith', 'suffering'] },
  { id: 'suffering', label: 'Suffering & Why God Allows Pain', keywords: ['suffering', 'suffer', 'why does god allow', 'why did god', 'why do bad things', 'bad things happen', 'why me', 'evil', 'trials', 'hard times', 'pain', 'unfair', 'tragedy'],
    overview: 'The Bible does not give a single tidy answer to suffering, but it gives something deeper: a God who is sovereign and good, who suffered Himself in Christ, who brings good out of evil, and who will finally end all pain.',
    points: [
      { title: 'Honest questions are allowed', text: 'Job, Habakkuk and the psalmists all asked “why?” God did not condemn their questions; He met them.', refs: ['Habakkuk 1:2-3', 'Job 42:5', 'Psalms 22:1'] },
      { title: 'God works through trials', text: 'Trials produce patience and mature faith; light affliction works an eternal weight of glory.', refs: ['James 1:2-4', 'Romans 5:3-5', '2 Corinthians 4:16-18', '1 Peter 1:6-7'] },
      { title: 'God will end suffering', text: 'The sufferings of this present time are not worthy to be compared with the glory to come. God will wipe away every tear.', refs: ['Romans 8:18', 'Romans 8:28', 'Revelation 21:4'] },
    ],
    practice: ['Bring your questions and grief directly to God in prayer.', 'Look at the cross — God did not stay distant from suffering.', 'Let your church carry you; you were not meant to suffer alone.'],
    prayer: 'Lord, I don’t understand this pain. Yet I bring it to You, the God who suffered for me. Hold me fast and work even this for good. Amen.',
    related: ['grief', 'hope', 'faith'] },
  { id: 'joy', label: 'Joy & Gratitude', keywords: ['joy', 'happy', 'happiness', 'joyful', 'rejoice', 'thankful', 'gratitude', 'thanksgiving', 'grateful', 'praise'],
    overview: 'Joy in Scripture is deeper than happiness — it is gladness in God that can coexist with sorrow. Gratitude is the habit that keeps joy alive.',
    points: [
      { title: 'Joy is rooted in God', text: 'In His presence is fulness of joy. The joy of the LORD is your strength.', refs: ['Psalms 16:11', 'Nehemiah 8:10', 'John 15:11'] },
      { title: 'Rejoice always', text: 'Paul, writing from prison: rejoice in the Lord alway. In everything give thanks.', refs: ['Philippians 4:4', '1 Thessalonians 5:16-18'] },
      { title: 'Joy after sorrow', text: 'Weeping may endure for a night, but joy comes in the morning.', refs: ['Psalms 30:5', 'Psalms 126:5-6', 'John 16:22'] },
    ],
    practice: ['Keep a daily gratitude list of three items.', 'Sing or read a psalm of praise (Psalm 100, 103).', 'Thank someone who has blessed you.'],
    prayer: 'Lord, in Your presence is fulness of joy. Thank You for every good gift. Fill me with gladness that circumstances cannot steal. Amen.',
    related: ['worship', 'peace'] },
  { id: 'loneliness', label: 'Loneliness', keywords: ['lonely', 'loneliness', 'alone', 'isolated', 'no friends', 'rejected', 'left out'],
    overview: 'God saw from the beginning that it is not good for man to be alone. He promises His own constant presence and places the lonely in families — the church.',
    points: [
      { title: 'God is with you', text: 'I will never leave thee, nor forsake thee. Lo, I am with you alway.', refs: ['Hebrews 13:5', 'Matthew 28:20', 'Deuteronomy 31:8'] },
      { title: 'God sets the solitary in families', text: 'God places the lonely in families and gathers His people into one body.', refs: ['Psalms 68:6', '1 Corinthians 12:26-27'] },
      { title: 'Jesus knows rejection', text: 'He was despised and rejected of men; His friends forsook Him. He understands.', refs: ['Isaiah 53:3', 'Mark 14:50', 'Hebrews 4:15'] },
    ],
    practice: ['Join a small group or serve in your church.', 'Reach out to one person this week — someone else may be lonely too.', 'Talk to God honestly about your loneliness.'],
    prayer: 'Lord, thank You that You never leave me. Lead me into real friendships and a church family, and help me be a friend to others. Amen.',
    related: ['depression', 'friendship'] },
  { id: 'friendship', label: 'Friendship', keywords: ['friend', 'friends', 'friendship', 'companion', 'community'],
    overview: 'The Bible celebrates deep friendship — David and Jonathan, Ruth and Naomi, Jesus and His disciples, whom He called friends.',
    points: [
      { title: 'True friends are loyal', text: 'A friend loveth at all times; there is a friend that sticketh closer than a brother.', refs: ['Proverbs 17:17', 'Proverbs 18:24', 'Ruth 1:16'] },
      { title: 'Friends sharpen each other', text: 'Iron sharpeneth iron. Faithful are the wounds of a friend.', refs: ['Proverbs 27:17', 'Proverbs 27:6', 'Ecclesiastes 4:9-10'] },
      { title: 'Jesus calls us friends', text: 'Greater love hath no man than this, that a man lay down his life for his friends. Ye are my friends.', refs: ['John 15:13-15'] },
    ],
    practice: ['Choose companions wisely (Proverbs 13:20).', 'Be the friend you want to have — show up, listen, pray.'],
    prayer: 'Jesus, thank You for calling me Your friend. Give me loyal, godly friendships and make me a faithful friend. Amen.',
    related: ['loneliness', 'love'] },
  { id: 'pride', label: 'Pride & Humility', keywords: ['pride', 'proud', 'humble', 'humility', 'ego', 'arrogant', 'arrogance'],
    overview: 'Pride puts self at the center; humility sees ourselves rightly before God. Scripture warns that pride goes before destruction, but God gives grace to the humble.',
    points: [
      { title: 'God resists the proud', text: 'Pride goeth before destruction. God resisteth the proud, but giveth grace unto the humble.', refs: ['Proverbs 16:18', 'James 4:6', '1 Peter 5:5'] },
      { title: 'Christ’s example', text: 'Let this mind be in you which was also in Christ Jesus, who humbled Himself to the cross.', refs: ['Philippians 2:3-8', 'John 13:14-15'] },
      { title: 'God lifts the humble', text: 'Humble yourselves in the sight of the Lord, and he shall lift you up.', refs: ['James 4:10', 'Micah 6:8', 'Luke 14:11'] },
    ],
    practice: ['Celebrate someone else’s success sincerely.', 'Ask for feedback and receive it without defending.', 'Serve in a hidden way.'],
    prayer: 'Lord, humble my heart. Help me esteem others better than myself and walk humbly with You. Amen.',
    related: ['grace', 'leadership'] },
  { id: 'holyspirit', label: 'The Holy Spirit', keywords: ['holy spirit', 'holy ghost', 'spirit filled', 'gifts of the spirit', 'fruit of the spirit', 'comforter', 'helper'],
    overview: 'The Holy Spirit is the third Person of the Trinity — not a force but God Himself, sent by the Father and the Son to dwell in believers, comfort, teach, empower and transform them.',
    points: [
      { title: 'The promised Comforter', text: 'Jesus promised another Comforter, the Spirit of truth, who would teach and remind the disciples of His words.', refs: ['John 14:16-17', 'John 14:26', 'John 16:13'] },
      { title: 'Power for witness', text: 'The Spirit came at Pentecost with power for the church to be Christ’s witnesses.', refs: ['Acts 1:8', 'Acts 2:1-4'] },
      { title: 'Fruit and gifts', text: 'The Spirit produces love, joy, peace and more, and gives gifts to build up the church.', refs: ['Galatians 5:22-23', '1 Corinthians 12:4-7', 'Romans 8:26'] },
    ],
    practice: ['Ask daily to be filled with the Spirit (Ephesians 5:18).', 'Pay attention to promptings to love, serve and speak.', 'Keep in step — confess quickly when you grieve the Spirit.'],
    prayer: 'Holy Spirit, fill me afresh. Produce Your fruit in me and empower me to love and witness boldly. Amen.',
    related: ['prayer', 'gifts'] },
  { id: 'heaven', label: 'Heaven & Eternal Life', keywords: ['heaven', 'afterlife', 'eternity', 'eternal', 'paradise', 'when we die', 'after death', 'resurrection'],
    overview: 'Scripture describes the Christian hope not as floating on clouds but as being with Christ at death and, finally, bodily resurrection into a renewed creation where God dwells with His people.',
    points: [
      { title: 'With Christ', text: 'To be absent from the body is to be present with the Lord. Jesus promised the thief, “To day shalt thou be with me in paradise.”', refs: ['2 Corinthians 5:8', 'Luke 23:43', 'Philippians 1:23'] },
      { title: 'A place prepared', text: 'In my Father’s house are many mansions… I go to prepare a place for you.', refs: ['John 14:1-3'] },
      { title: 'All things new', text: 'Resurrection bodies and a new heaven and earth, with no more death, sorrow or pain.', refs: ['1 Corinthians 15:51-54', 'Revelation 21:1-4', 'Revelation 22:3-5'] },
    ],
    practice: ['Read Revelation 21–22 slowly.', 'Let eternal hope shape how you spend today (Colossians 3:1-2).'],
    prayer: 'Lord Jesus, thank You for preparing a place for me. Fix my eyes on the hope of being with You forever. Amen.',
    related: ['hope', 'grief', 'salvation'] },
  { id: 'identity', label: 'Identity & Self-Worth', keywords: ['identity', 'self worth', 'self-worth', 'worth', 'value', 'insecure', 'insecurity', 'ugly', 'not good enough', 'who am i', 'confidence'],
    overview: 'Your worth is not based on performance, appearance or others’ opinions, but on being made in God’s image and loved by Him. In Christ, believers receive a new identity: chosen, adopted, forgiven and beloved.',
    points: [
      { title: 'Fearfully and wonderfully made', text: 'God formed you in your mother’s womb; you are made in His image.', refs: ['Psalms 139:13-14', 'Genesis 1:27'] },
      { title: 'Children of God', text: 'Behold what manner of love the Father has given us, that we should be called the sons of God.', refs: ['1 John 3:1', 'John 1:12', 'Galatians 4:7'] },
      { title: 'A new creation', text: 'If any man be in Christ, he is a new creature; old things are passed away. You are a chosen generation.', refs: ['2 Corinthians 5:17', '1 Peter 2:9', 'Ephesians 1:4-6'] },
    ],
    practice: ['Write out “In Christ I am…” statements from Ephesians 1.', 'Notice when you seek worth from approval, and bring it to God.'],
    prayer: 'Father, thank You that I am Your child, made and loved by You. Help me rest in who You say I am. Amen.',
    related: ['love', 'grace'] },
  { id: 'patience', label: 'Patience & Waiting', keywords: ['patience', 'patient', 'wait', 'waiting', 'impatient', 'how long'],
    overview: 'Waiting is one of the main classrooms of faith. Abraham, Joseph, David and Simeon all waited years for God’s promises — and God was working the entire time.',
    points: [
      { title: 'Wait on the LORD', text: 'Be of good courage, and He shall strengthen your heart. They that wait upon the LORD shall renew their strength.', refs: ['Psalms 27:14', 'Isaiah 40:31'] },
      { title: 'God’s timing is not slow', text: 'The Lord is not slack concerning His promise; to every thing there is a season.', refs: ['2 Peter 3:9', 'Ecclesiastes 3:1', 'Habakkuk 2:3'] },
      { title: 'Patience is fruit', text: 'Patience is part of the fruit of the Spirit, and trials work patience in us.', refs: ['Galatians 5:22', 'James 1:3-4', 'Romans 12:12'] },
    ],
    practice: ['Ask, “What is God forming in me while I wait?”', 'Serve someone else while you wait.'],
    prayer: 'Lord, I am tired of waiting. Strengthen my heart and help me trust Your timing. Amen.',
    related: ['trust', 'hope'] },
  { id: 'obedience', label: 'Obedience & Holiness', keywords: ['obedience', 'obey', 'holy', 'holiness', 'righteous', 'righteousness', 'godly', 'purity', 'pure'],
    overview: 'Obedience in Scripture is the fruit of love, not the root of salvation. Jesus said, “If ye love me, keep my commandments.” Holiness means being set apart for God.',
    points: [
      { title: 'Love shows in obedience', text: 'If ye love me, keep my commandments. Be doers of the word, not hearers only.', refs: ['John 14:15', 'James 1:22-25', '1 John 5:3'] },
      { title: 'Be holy', text: 'As He which hath called you is holy, so be ye holy in all manner of conversation.', refs: ['1 Peter 1:15-16', 'Hebrews 12:14'] },
      { title: 'Transformed, not conformed', text: 'Present your bodies a living sacrifice and be transformed by the renewing of your mind.', refs: ['Romans 12:1-2', 'Philippians 2:12-13'] },
    ],
    practice: ['Act on one thing you read in Scripture today.', 'Remove one influence that pulls you away from God.'],
    prayer: 'Lord, I want to obey You out of love. Set me apart for Yourself and work in me both to will and to do Your pleasure. Amen.',
    related: ['temptation', 'love'] },
  { id: 'worship', label: 'Worship', keywords: ['worship', 'praise', 'singing', 'adoration', 'glorify'],
    overview: 'Worship is giving God the honor He deserves with our whole lives — in song, in prayer, in gathered praise, and in everyday obedience.',
    points: [
      { title: 'In spirit and in truth', text: 'God seeks worshippers who worship in spirit and in truth.', refs: ['John 4:23-24'] },
      { title: 'With all creation', text: 'Let every thing that hath breath praise the LORD. Enter His gates with thanksgiving.', refs: ['Psalms 150:6', 'Psalms 100:1-4'] },
      { title: 'With our whole lives', text: 'Present your bodies a living sacrifice — your reasonable service of worship.', refs: ['Romans 12:1', 'Colossians 3:16-17'] },
    ],
    practice: ['Listen to or sing a hymn and pray its words.', 'Turn a task today into an offering to God.'],
    prayer: 'Lord, You alone are worthy. Receive my praise and my whole life as worship. Amen.',
    related: ['joy', 'prayer'] },
  { id: 'church', label: 'The Church & Community', keywords: ['church', 'fellowship', 'congregation', 'body of christ', 'small group'],
    overview: 'The church is not a building but the people of God — the body of Christ, a family of believers called to worship, grow, serve and witness together.',
    points: [
      { title: 'One body, many members', text: 'Every believer is a member with a role; the body needs every part.', refs: ['1 Corinthians 12:12-27', 'Romans 12:4-5'] },
      { title: 'Devoted together', text: 'The early church continued in the apostles’ doctrine, fellowship, breaking of bread and prayers.', refs: ['Acts 2:42-47'] },
      { title: 'Don’t give up meeting', text: 'Consider one another to provoke unto love and good works, not forsaking the assembling together.', refs: ['Hebrews 10:24-25'] },
    ],
    practice: ['Commit to a local church and attend consistently.', 'Find one way to serve.'],
    prayer: 'Lord, thank You for Your church. Help me to love, serve and grow with Your people. Amen.',
    related: ['friendship', 'worship'] },
  { id: 'evangelism', label: 'Sharing Your Faith', keywords: ['evangelism', 'witness', 'share my faith', 'share the gospel', 'great commission', 'missions', 'witnessing'],
    overview: 'Jesus commissioned His followers to make disciples of all nations. Sharing faith is simply telling others what God has done and pointing them to Jesus — with gentleness and respect.',
    points: [
      { title: 'The commission', text: 'Go ye therefore, and teach all nations… and, lo, I am with you alway.', refs: ['Matthew 28:18-20', 'Acts 1:8'] },
      { title: 'Not ashamed', text: 'The gospel is the power of God unto salvation to every one that believeth.', refs: ['Romans 1:16', '2 Timothy 1:8'] },
      { title: 'Be ready, be gentle', text: 'Be ready always to give an answer for the hope within you, with meekness and fear.', refs: ['1 Peter 3:15', 'Colossians 4:5-6'] },
    ],
    practice: ['Write your three-minute testimony: before, how you met Christ, after.', 'Pray for three people by name who don’t know Jesus.'],
    prayer: 'Lord, give me boldness and love to share Jesus naturally, and open hearts around me. Amen.',
    related: ['salvation', 'church'] },
  { id: 'kindness', label: 'Kindness & Serving Others', keywords: ['serve', 'serving', 'service', 'volunteer', 'help others', 'poor', 'needy', 'compassion', 'justice'],
    overview: 'Jesus came not to be served but to serve. Serving others — especially the poor, the stranger and the vulnerable — is service to Christ Himself.',
    points: [
      { title: 'Jesus our example', text: 'The Son of man came not to be ministered unto, but to minister. He washed His disciples’ feet.', refs: ['Mark 10:43-45', 'John 13:12-15'] },
      { title: 'Serving the least', text: 'Inasmuch as ye have done it unto one of the least of these my brethren, ye have done it unto me.', refs: ['Matthew 25:35-40', 'James 1:27'] },
      { title: 'Do justly, love mercy', text: 'God requires us to do justly, love mercy and walk humbly with Him.', refs: ['Micah 6:8', 'Isaiah 1:17', 'Galatians 6:9-10'] },
    ],
    practice: ['Look for one need in your neighborhood and meet it this week.', 'Give your time, not just money.'],
    prayer: 'Lord Jesus, give me a servant’s heart. Open my eyes to the needs around me and help me love in deed and truth. Amen.',
    related: ['love', 'pride'] },
  { id: 'contentment', label: 'Contentment & Envy', keywords: ['content', 'contentment', 'envy', 'jealous', 'jealousy', 'comparison', 'compare', 'covet', 'greed'],
    overview: 'Contentment is learned, not natural. Paul learned to be content whether full or hungry, because Christ was enough.',
    points: [
      { title: 'Contentment is learned', text: 'I have learned, in whatsoever state I am, therewith to be content.', refs: ['Philippians 4:11-13'] },
      { title: 'God is enough', text: 'Be content with such things as ye have: for he hath said, I will never leave thee.', refs: ['Hebrews 13:5', 'Psalms 73:25-26'] },
      { title: 'Envy rots', text: 'Envy is the rottenness of the bones; thou shalt not covet.', refs: ['Proverbs 14:30', 'Exodus 20:17', 'James 3:16'] },
    ],
    practice: ['Limit scrolling that fuels comparison.', 'Thank God specifically for what you have.'],
    prayer: 'Lord, You are my portion. Teach me contentment, free me from envy, and fill me with gratitude. Amen.',
    related: ['money', 'joy'] },
  { id: 'perseverance', label: 'Perseverance', keywords: ['persevere', 'perseverance', 'endure', 'endurance', 'keep going', 'quit', 'quitting', 'tired of trying'],
    overview: 'The Christian life is described as a race. God calls us to run with endurance, keeping our eyes on Jesus, and promises a harvest to those who do not give up.',
    points: [
      { title: 'Run with eyes on Jesus', text: 'Lay aside every weight and run with patience, looking unto Jesus.', refs: ['Hebrews 12:1-3'] },
      { title: 'Don’t grow weary', text: 'In due season we shall reap, if we faint not.', refs: ['Galatians 6:9', '1 Corinthians 15:58'] },
      { title: 'God finishes what He starts', text: 'He which hath begun a good work in you will perform it.', refs: ['Philippians 1:6', 'Philippians 3:13-14', 'James 1:12'] },
    ],
    practice: ['Focus on faithfulness today, not the whole distance.', 'Find a running partner in faith.'],
    prayer: 'Lord, keep me going. Fix my eyes on Jesus and finish the good work You began in me. Amen.',
    related: ['strength', 'patience'] },
  { id: 'enemies', label: 'Enemies & Being Mistreated', keywords: ['enemy', 'enemies', 'persecution', 'persecuted', 'bully', 'bullied', 'bullying', 'mistreated', 'slander', 'lying about me', 'lies about me', 'gossiping about me', 'hate me', 'hates me', 'revenge', 'unfair treatment', 'treat me badly', 'attacked', 'betrayal'],
    overview: 'Jesus was slandered, betrayed and mistreated, so He understands. Scripture neither tells us to pretend wrongs don’t hurt nor to retaliate; it calls us to entrust ourselves to God who judges justly, to respond with integrity, and — remarkably — to love and pray for those who wrong us.',
    points: [
      { title: 'God sees and will judge justly', text: 'When reviled, Jesus did not revile back but committed Himself to the One who judges righteously. Vengeance belongs to God, not to us.', refs: ['1 Peter 2:21-23', 'Romans 12:19', 'Psalms 37:5-7'] },
      { title: 'Answer with integrity, not imitation', text: 'Overcome evil with good. A soft answer turns away wrath, and a good conscience shames those who speak falsely against you.', refs: ['Romans 12:17-21', 'Proverbs 15:1', '1 Peter 3:16'] },
      { title: 'Love and pray for them', text: 'Jesus calls us to love our enemies and pray for those who persecute us — not because the wrong is small, but because we are children of a merciful Father.', refs: ['Matthew 5:43-45', 'Luke 6:27-28', 'Luke 23:34'] },
    ],
    practice: ['Pray honestly about the situation — the psalms show it is fine to tell God exactly how unfair it feels.', 'Keep your own conduct and words above reproach; document facts calmly if it is a workplace issue.', 'Address it directly and privately if it is safe (Matthew 18:15), and involve the right authority (a manager, HR, a pastor) when needed.', 'Pray one sincere blessing over the person each day.'],
    prayer: 'Lord, You see what is being said and done to me. I trust You to defend me and to judge justly. Keep my heart free from bitterness and my words full of grace, and help me to love even here. Amen.',
    related: ['forgiveness', 'anger', 'honesty'] },
  { id: 'honesty', label: 'Honesty & Integrity', keywords: ['lie', 'lies', 'lying', 'liar', 'lied', 'honest', 'honesty', 'truthful', 'deceive', 'deceit', 'deception', 'cheat', 'cheating', 'integrity', 'steal', 'stealing'],
    overview: 'God is truth and cannot lie, and He calls His people to be people of their word. Integrity means being the same person in private as in public.',
    points: [
      { title: 'God delights in truth', text: 'Lying lips are an abomination to the LORD, but those who deal truly are His delight. Thou shalt not bear false witness.', refs: ['Proverbs 12:22', 'Exodus 20:16', 'Psalms 15:1-2'] },
      { title: 'Put away lying', text: 'Because we belong to one another in Christ, put away lying and speak every man truth with his neighbour.', refs: ['Ephesians 4:25', 'Colossians 3:9-10'] },
      { title: 'Integrity guides and protects', text: 'The integrity of the upright shall guide them; he that walketh uprightly walketh surely.', refs: ['Proverbs 11:3', 'Proverbs 10:9', 'Luke 16:10'] },
    ],
    practice: ['Tell the truth even when it costs you something small — integrity is built in small moments.', 'If you have deceived someone, confess and make it right where you can.', 'Let your yes be yes and your no be no (Matthew 5:37).'],
    prayer: 'God of truth, make me a person of integrity. Guard my lips from deceit, and help me walk uprightly in private and in public. Amen.',
    related: ['words', 'obedience'] },
  { id: 'words', label: 'Our Words & the Tongue', keywords: ['gossip', 'gossiping', 'tongue', 'speech', 'swearing', 'cursing', 'cuss', 'words', 'insult', 'insults', 'criticize', 'complain', 'complaining'],
    overview: 'James says the tongue is small but powerful — it can bless or curse, build up or burn down. Our words reveal and shape our hearts.',
    points: [
      { title: 'Words have power', text: 'Death and life are in the power of the tongue. The tongue is a little member that boasts great things — a small fire can kindle a great forest.', refs: ['Proverbs 18:21', 'James 3:5-6'] },
      { title: 'Words come from the heart', text: 'Out of the abundance of the heart the mouth speaks; changing our speech starts with a changed heart.', refs: ['Luke 6:45', 'Matthew 12:36-37'] },
      { title: 'Speak to build up', text: 'Let no corrupt communication proceed out of your mouth, but that which is good to the use of edifying, that it may minister grace to the hearers.', refs: ['Ephesians 4:29', 'Colossians 4:6', 'Proverbs 16:24'] },
    ],
    practice: ['Before speaking ask: Is it true? Is it kind? Is it necessary?', 'Refuse to pass on gossip — let it stop with you (Proverbs 26:20).', 'Speak one sincere word of encouragement to someone every day.'],
    prayer: 'Set a watch, O LORD, before my mouth (Psalm 141:3). Let my words be full of grace and truth, building others up. Amen.',
    related: ['honesty', 'anger'] },
  { id: 'justice', label: 'Justice & the Poor', keywords: ['justice', 'injustice', 'oppression', 'oppressed', 'racism', 'corruption', 'poor people', 'refugee', 'widow', 'orphan', 'orphans'],
    overview: 'Justice flows from God’s own character. Throughout Scripture He defends the poor, the widow, the orphan and the stranger, and calls His people to do the same.',
    points: [
      { title: 'God loves justice', text: 'The LORD loves righteousness and judgment; He executes justice for the oppressed and defends the fatherless and widow.', refs: ['Psalms 33:5', 'Psalms 146:7-9', 'Deuteronomy 10:18'] },
      { title: 'God’s people pursue it', text: 'Seek judgment, relieve the oppressed, plead for the widow. Let judgment run down as waters.', refs: ['Isaiah 1:17', 'Amos 5:24', 'Micah 6:8'] },
      { title: 'Jesus brings good news to the poor', text: 'Jesus announced His mission: to preach the gospel to the poor and set at liberty them that are bruised.', refs: ['Luke 4:18', 'James 2:15-17', 'Proverbs 31:8-9'] },
    ],
    practice: ['Learn about a need in your community and give time or resources.', 'Speak up for someone who has no voice.', 'Pray for leaders to rule justly (1 Timothy 2:1-2).'],
    prayer: 'Righteous God, give me Your heart for the poor and oppressed. Use me to do justly, love mercy and walk humbly with You. Amen.',
    related: ['kindness'] },
  { id: 'baptism', label: 'Baptism', keywords: ['baptism', 'baptized', 'baptised', 'baptize'],
    overview: 'Baptism is an outward sign of an inward reality — identifying with Christ’s death, burial and resurrection. Jesus commanded it, and the early church practiced it with new believers.',
    points: [
      { title: 'Commanded by Jesus', text: 'Make disciples, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost.', refs: ['Matthew 28:19', 'Matthew 3:13-17'] },
      { title: 'Union with Christ', text: 'We are buried with Him by baptism into death, that we should walk in newness of life.', refs: ['Romans 6:3-4', 'Colossians 2:12', 'Galatians 3:27'] },
      { title: 'A response to the gospel', text: 'At Pentecost Peter urged, “Repent, and be baptized every one of you.”', refs: ['Acts 2:38-41', 'Acts 8:36-38'] },
    ],
    practice: ['Talk to your pastor about baptism.', 'Share your story with family and friends.'],
    prayer: 'Lord, thank You for new life in Christ. Help me follow You in obedience and walk in newness of life. Amen.',
    related: ['salvation', 'church'] },
  { id: 'fasting', label: 'Fasting', keywords: ['fast', 'fasting'],
    overview: 'Fasting is voluntarily going without food (or something else) for a time to seek God more intently. Jesus assumed His followers would fast and taught them to do it humbly.',
    points: [
      { title: 'When you fast', text: 'Jesus said “when ye fast,” not “if,” and warned against doing it for show.', refs: ['Matthew 6:16-18'] },
      { title: 'Fasting with prayer', text: 'Esther, Nehemiah, Daniel and the early church fasted when seeking God for direction or deliverance.', refs: ['Esther 4:16', 'Nehemiah 1:4', 'Acts 13:2-3'] },
      { title: 'The fast God chooses', text: 'True fasting is joined with justice and mercy to the oppressed.', refs: ['Isaiah 58:6-7'] },
    ],
    practice: ['Start small — skip one meal and pray during that time.', 'If you have health conditions, are pregnant, or have a history of eating struggles, consult a doctor and consider fasting from media or other things instead.'],
    prayer: 'Lord, I hunger for You more than food. Meet me as I seek You. Amen.',
    related: ['prayer'] },
];
