/**
 * Builds data/kjv/<bookId>.json (one small file per book) plus
 * data/kjv/index.js (a static require map) from assets/kjv.json.
 *
 * Why per-book instead of one big file: requiring a single ~4.3MB JSON at
 * app-startup module-load time (before any screen even renders) is a known
 * React Native crash risk — Hermes/Metro can choke on very large inline
 * JSON literals, and even when it doesn't crash outright it forces the
 * entire Bible into memory on every launch. Splitting into 66 files (each
 * well under 150KB) means only the book actually being read gets parsed
 * into memory, on demand.
 *
 * assets/kjv.json is an array of 66 books (canonical Bible order) shaped:
 *   { abbrev: 'gn', name: 'Genesis', chapters: [ [verse1, verse2, ...], ... ] }
 * data/books.js is in the same canonical order, so we zip by position.
 *
 * Run with: node scripts/buildKjvIndex.js
 */
const fs = require('fs');
const path = require('path');

const { BOOKS } = require('../data/books');

function cleanVerseText(raw) {
  let text = String(raw || '');
  // Remove marginal/translator notes: "{...: ...}"
  text = text.replace(/\{[^{}]*:[^{}]*\}/g, '');
  // Unwrap supplied words: "{word}" -> "word"
  text = text.replace(/\{([^{}]*)\}/g, '$1');
  // Collapse whitespace created by removals and trim stray space before punctuation
  text = text.replace(/\s{2,}/g, ' ').replace(/\s+([,.;:!?])/g, '$1').trim();
  return text;
}

function main() {
  const srcPath = path.join(__dirname, 'source-data/kjv.json');
  const raw = fs.readFileSync(srcPath, 'utf8').replace(/^\uFEFF/, '');
  const kjv = JSON.parse(raw);

  if (kjv.length !== BOOKS.length) {
    console.warn(`Warning: source has ${kjv.length} books, data/books.js has ${BOOKS.length}. Proceeding by position, extra entries ignored.`);
  }

  const outDir = path.join(__dirname, '../data/kjv');
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  let totalVerses = 0;
  const bookIds = [];

  BOOKS.forEach((book, i) => {
    const src = kjv[i];
    if (!src) {
      console.warn(`Missing source book for ${book.id} (${book.name})`);
      return;
    }
    const chapters = {};
    src.chapters.forEach((versesArr, chIdx) => {
      const chapterNum = chIdx + 1;
      const verses = {};
      versesArr.forEach((text, vIdx) => {
        verses[vIdx + 1] = cleanVerseText(text);
        totalVerses++;
      });
      chapters[chapterNum] = verses;
    });
    fs.writeFileSync(path.join(outDir, `${book.id}.json`), JSON.stringify(chapters));
    bookIds.push(book.id);
  });

  // A static require map. Metro (React Native's bundler) cannot resolve
  // dynamically-constructed require() paths like require('./' + id + '.json')
  // — every path has to appear literally in the source for Metro to include
  // it in the bundle. Wrapping each in a function keeps it lazy: the JSON is
  // only actually parsed the first time that specific book is requested.
  const lines = bookIds.map((id) => `  ${JSON.stringify(id)}: () => require('./${id}.json'),`);
  const indexSrc = `// AUTO-GENERATED by scripts/buildKjvIndex.js — do not edit by hand.\nmodule.exports = {\n${lines.join('\n')}\n};\n`;
  fs.writeFileSync(path.join(outDir, 'index.js'), indexSrc);

  console.log(`Wrote ${bookIds.length} book files + index.js to ${outDir}`);
  console.log(`Total verses: ${totalVerses}`);
}

main();
